### ISSUE TITLE
Test Job (Lambda) fails although the smrt pipeline seems to execute successfully

### ISSUE THREAD

**Issue by adwicki** [PacificBiosciences/SMRT-Analysis#131]
We encountered the issue with smrt portal v2.1.1 and now again with the new version v2.2.0.
The lambda job seems to execute almost completely and the log states the following information:
```
[INFO] 2014-09-09 11:56:17,231 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully

[INFO] 2014-09-09 11:56:17,232 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code 0

[INFO] 2014-09-09 11:56:17,232 [root main 336] Successfully exiting smrtpipe version v1.85.133289 with exit code 0 in 258.63 seconds (4.31 minutes)
```
So it seems the pipeline finishes, but the job status in the smrt portal still shows "Submitted".
After maybe an hour the job status would switch to "Failed".
We then tried to investigate the failure using the master log. A search for the keyword "error" reveals the following errors:
```
[DEBUG] 2014-09-09 11:52:02,820 [SMRTpipe.engine.DistributableTasks __init__ 199] Creating Gather task with args: () kw: {'constructCommands': <function myGatherFunction at 0x29f4aa0>, 'outputs': {'toGather': URL file://jobId/data/aligned_reads.cmp.h5#presorted Path data/aligned_reads.cmp.h5}, '_taskTypeName': 'GatherNonEmptyCmpH5', 'errors': {'AssertionError: No alignments in the CmpH5 file(s).': 'Gather Error. No Reads Mapped to the reference; no further analysis is possible'}, 'nproc': 2}

[DEBUG] 2014-09-09 11:52:02,821 [SMRTpipe.engine.DistributableTasks __init__ 199] Creating Gather task with args: () kw: {'constructCommands': <function myGatherFunction at 0x29f4c80>, 'outputs': {'toGather': URL file://jobId/data/aligned_reads.cmp.h5#presorted Path data/aligned_reads.cmp.h5}, '_taskTypeName': 'GatherNonEmptyCmpH5', 'errors': {'AssertionError: No alignments in the CmpH5 file(s).': 'Gather Error. No Reads Mapped to the reference; no further analysis is possible'}, 'nproc': 2}
```
There were no other error messages in the log-file. We would it appreciate it very much if you could give us some assistance to get the smrt portal up and running.
Thanks in advance!
PS: Please let us know if you need any further information.

**Comment by lancetxiao** [comment]
[Uploading -opt-smrtanalysis-userdata-jobs-016-log-master.txt…]()
Test Job (Lambda) sucessfully but my own test fails!
thanks a lot. xiexie!
