### ISSUE TITLE
P_fetch error

### ISSUE THREAD

**Issue by JinchuVijay** [PacificBiosciences/SMRT-Analysis#134]
Hi
I am new to pacbio technology. Using downloaded dataset of e coli, I tried to remove barcodes using SMRT pipeline.
But it is showing errors. Details of error log is below. Please help 
[INFO] 2014-09-16 10:18:45,752 [root main 270] Starting smrtpipe.py : v1.79.127046
[INFO] 2014-09-16 10:18:45,752 [root main 271] Using Python : v2.7.3
[INFO] 2014-09-16 10:18:45,768 [root main 272] Platform info Linux-2.6.32-358.el6.x86_64-x86_64-with-redhat-6.4-Santiago
[INFO] 2014-09-16 10:18:45,778 [root main 273] Running on NGSNODE4.scigenom.com
[INFO] 2014-09-16 10:18:45,778 [root main 274] Process id 19071
[INFO] 2014-09-16 10:18:45,778 [pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/etc/config.xml
[INFO] 2014-09-16 10:18:45,779 [pbpy.smrtpipe.SmrtPipeConfig __autoLoad 110] Loading configuration from /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/etc/smrtpipe.rc
[INFO] 2014-09-16 10:18:45,780 [pbpy.smrtpipe.SmrtPipeConfig __setAlgorithmParametersPath 209] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/etc/algorithm_parameters/2013-09
[INFO] 2014-09-16 10:18:45,893 [pbpy.smrtpipe.SmrtPipeMain _sanityCheck 760] Found file /RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12/Analysis_Results/m130404_014004_sidney_c100506902550000001823076808221337_s1_p0.1.bax.h5 2339464203 bytes
[INFO] 2014-09-16 10:18:46,014 [pbpy.smrtpipe.SmrtPipeMain _sanityCheck 760] Found file /RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12/Analysis_Results/m130404_014004_sidney_c100506902550000001823076808221337_s1_p0.2.bax.h5 2173099882 bytes
[INFO] 2014-09-16 10:18:46,137 [pbpy.smrtpipe.SmrtPipeMain _sanityCheck 760] Found file /RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12/Analysis_Results/m130404_014004_sidney_c100506902550000001823076808221337_s1_p0.3.bax.h5 2703276055 bytes
[INFO] 2014-09-16 10:18:46,138 [smrtpipe.status _sanityCheck 765] Successfully found 3 files in xml:/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438/input.xml
[INFO] 2014-09-16 10:18:46,138 [pbpy.io.SecondaryConfig _loadFromFile 25] Loading SecondaryConfig from /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/etc/config.xml
[INFO] 2014-09-16 10:18:46,139 [pbpy.smrtpipe.SmrtPipeConfig __autoLoad 110] Loading configuration from /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/etc/smrtpipe.rc
[INFO] 2014-09-16 10:18:46,140 [pbpy.smrtpipe.SmrtPipeConfig __setAlgorithmParametersPath 209] ALGO_PARAMS key not found in smrtpipe.rc - using latest bundle: /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/etc/algorithm_parameters/2013-09
[INFO] 2014-09-16 10:18:46,141 [pbpy.smrtpipe.SmrtPipeContext __init__ 84] SmrtPipeConfig Summary:
TMP = /opt/smartanalysis-2.1/smrtanalysis/tmpdir 
PROGRESS_URL = http://192.168.1.196:8080/smrtportal/api 
CLUSTER_MANAGER = BASH 
HOST_PORT = 8080 
NCHUNKS = 64 
ALGO_PARAMS_PATH = /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/etc/algorithm_parameters/2013-09
MAX_SLOTS = 256 
ca_distribute.hgap = useGrid:0, scriptOnGrid:1, frgCorrOnGrid:1, ovlCorrOnGrid:1 
CLOUD_LARGE_FILE_CUTOFF = 10MB 
SMRTANALYSIS_VERSION = v2.1.1 
INPUT_HDF5_EXT = bas.h5 
SMRTPIPE_VERSION = v2.1.1.128436 
HOST_NAME = 192.168.1.196 
DENOVO_READ_SCOPES = small: 0.15, large:15, huge:1700 
NPROC = 20 
DENOVO_GENOME_SCOPES = small:100, large:1000, huge:40000 
NJOBS = 64 
CLOUD = False 
REFERENCE_SCOPES = small:10, large:1000, veryLarge:100000, huge:10000000 
MAX_THREADS = 8 
HEARTBEAT_FREQ = 60 
VIS_HOST = 192.168.1.196 
VIS_PORT = 8080 
SHARED_DIR = /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/userdata/shared_dir 
DEBUG = False 
ca_distribute.pb2ca = useGrid:1, scriptOnGrid:1, frgCorrOnGrid:1, ovlCorrOnGrid:1 
SETTINGS_PATH = . 
EXIT_ON_FAILURE = False 
CLOUD_CHUNKS_PER_PROC = 2 
READ_SCOPES = small:3.6, large:100, veryLarge:10000, huge:1000000 
MAX_CHUNKS = 64 
ASSEMBLY_HOME = /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis 
DATA_ROOT = /mnt 
VIS_NAMESPACE = 
IPY = ipy -X:ColorfulConsole 
TOC_HTML_NAME = index.html 
[WARNING] 2014-09-16 10:18:46,147 [pbpy.smrtpipe.SmrtPipeSettings _importSettings 195] Parameter global.control is missing a value
[INFO] 2014-09-16 10:18:46,149 [pbpy.smrtpipe.SmrtPipeContext initializeContext 229] SmrtPipeSettings Summary:
settings loaded from file /root
p_barcode.moduleName = P_Barcode 
global.fetch = common/protocols/preprocessing/Fetch.1.xml 
p_ampliconassembly.minLength = 1000 
global.version = 1 
p_barcode.mode = paired 
global.name = Barcode_longamplicontest 
p_fetch.description = Sets up inputs 
p_ampliconassembly.maxReads = 40000 
p_ampliconassembly.description = LongAmpliconAnalysis calls phased consensus sequences from pooled amplicon sequence data. Up to 20 distinct amplicons can pooled. Reads are clustered into high-level groups, then each group is phased and consensus is called using the Quiver algorithm. Addidtionally if the sample is barcoded, separate calls are made for each barcode.
p_fetch.moduleName = P_Fetch 
p_ampliconassembly.moduleName = P_AmpliconAssembly 
global.barcode = common/protocols/barcode/Barcode.1.xml 
global.description = Determine phased consensus sequences for pooled amplicon data. Optionally splits reads by barcode. 
global.state = active 
p_barcode.score = 0 
p_barcode.barcode.fasta = common/references/pacbio_barcodes_paired 
global.amplicon = common/protocols/consensus/LongAmpliconAnalysis.1.xml 
[INFO] 2014-09-16 10:18:46,151 [pbpy.smrtpipe.SmrtDataService setupOutputDirectories 132] Creating /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438/data
[INFO] 2014-09-16 10:18:46,152 [pbpy.smrtpipe.SmrtDataService setupOutputDirectories 132] Creating /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438/results
[INFO] 2014-09-16 10:18:46,153 [pbpy.smrtpipe.SmrtDataService setupOutputDirectories 136] Completed setting up DataServices in /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438
[INFO] 2014-09-16 10:18:46,153 [pbpy.smrtpipe.SmrtPipeContext initializeContext 251] Input data is [ file//RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12 ]
[INFO] 2014-09-16 10:18:46,153 [pbpy.smrtpipe.SmrtPipeContext initializeContext 255] Configuration override for PROGRESS_URL: Old: --> New: http://192.168.1.196:8080/smrtportal/api
[INFO] 2014-09-16 10:18:46,156 [pbpy.smrtpipe.SmrtPipeContext initializeContext 268] Changing working directory to /opt/smartanalysis-2.1/smrtanalysis/tmpdir/tmpP9qNv9
[INFO] 2014-09-16 10:18:46,187 [pbpy.smrtpipe.SmrtPipeContext movieFiles 365] Pulling data from tags: primaryAnalysisProtocol=['Analysis_Results']
[INFO] 2014-09-16 10:18:46,187 [pbpy.smrtpipe.SmrtPipeContext movieFiles 385] Found /RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12/Analysis_Results/m130404_014004_sidney_c100506902550000001823076808221337_s1_p0.1.bax.h5 (2339464203 bytes)
[INFO] 2014-09-16 10:18:46,188 [pbpy.smrtpipe.SmrtPipeContext movieFiles 385] Found /RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12/Analysis_Results/m130404_014004_sidney_c100506902550000001823076808221337_s1_p0.2.bax.h5 (2173099882 bytes)
[INFO] 2014-09-16 10:18:46,188 [pbpy.smrtpipe.SmrtPipeContext movieFiles 385] Found /RELOAD/STAFF/SHARED/CommercialProjects/NGS_P209_CCMB_Apple/Pacbio/ecoliK12/Analysis_Results/m130404_014004_sidney_c100506902550000001823076808221337_s1_p0.3.bax.h5 (2703276055 bytes)
[WARNING] 2014-09-16 10:18:46,690 [pbpy.smrtpipe.SmrtPipeMain _getBasVersions 395] Unable to correctly Parse the basH5 versions. Allowing job to proceed, but please fix the compatibility matrix under $SEYMOUR_HOME/common/etc. Error unable to create file (File accessability: Unable to open file)
[INFO] 2014-09-16 10:18:46,691 [smrtpipe.status run 476] smrtpipe.py running on NGSNODE4
[INFO] 2014-09-16 10:18:46,692 [smrtpipe.status run 492] SMRT Analysis v2.1.1 / SMRTpipe 1.79.127046
[INFO] 2014-09-16 10:18:46,692 [pbpy.smrtpipe.SmrtPipeMain run 495] Starting smrtpipe version 1.79.127046
[INFO] 2014-09-16 10:18:47,668 [pbpy.smrtpipe.SmrtPipeMain _dynamicallyLoadModule 803] Dynamically Loaded P_Fetch module
[INFO] 2014-09-16 10:18:47,672 [pbpy.smrtpipe.SmrtPipeMain _loadModules 183] Loaded module P_Fetch v2.3.127046 and validated settings.
[INFO] 2014-09-16 10:18:47,739 [pbpy.smrtpipe.SmrtPipeMain _dynamicallyLoadModule 803] Dynamically Loaded P_Barcode module
[INFO] 2014-09-16 10:18:47,742 [pbpy.smrtpipe.modules.P_Barcode validateSettings 78] Trying barcode fasta file as reference repo: /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/references/pacbio_barcodes_paired
[INFO] 2014-09-16 10:18:47,793 [pbpy.smrtpipe.modules.P_Barcode validateSettings 80] Barcode fasta file resolved: /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/references/pacbio_barcodes_paired/sequence/pacbio_barcodes_paired.fasta
[INFO] 2014-09-16 10:18:47,797 [pbpy.smrtpipe.SmrtPipeMain _loadModules 183] Loaded module P_Barcode v1.6.128003 and validated settings.
[INFO] 2014-09-16 10:18:47,798 [pbpy.smrtpipe.SmrtPipeMain _loadModules 187] Setting barcodeFasta in ReportService to /opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/references/pacbio_barcodes_paired/sequence/pacbio_barcodes_paired.fasta
[INFO] 2014-09-16 10:18:47,800 [pbpy.smrtpipe.SmrtPipeMain _dynamicallyLoadModule 803] Dynamically Loaded P_AmpliconAssembly module
[INFO] 2014-09-16 10:18:47,804 [pbpy.smrtpipe.SmrtPipeMain _loadModules 183] Loaded module P_AmpliconAssembly v1.12.125061 and validated settings.
[INFO] 2014-09-16 10:18:47,807 [pbpy.smrtpipe.SmrtDataService writeTo 424] Writing 6 items to DataStore in {'smrt.data.xmlparam': , 'smrt.output.log': '/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438/log', 'smrt.data.cmdline': , 'smrt.output.root': '/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438', 'smrt.output.results': '/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438/results', 'smrt.output.data': '/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/common/jobs/016/016438/data'}
[INFO] 2014-09-16 10:18:47,810 [pbpy.smrtpipe.SmrtPipeMain _runTasks 262] Skipping PreWorkflow as it contains zero tasks
[INFO] 2014-09-16 10:18:47,811 [pbpy.smrtpipe.SmrtPipeMain _runTasks 265] Loading 9 tasks into Workflow
[INFO] 2014-09-16 10:18:48,362 [pbpy.smrtpipe.SmrtPipeMain _runTasks 274] Executing workflow Workflow
[INFO] 2014-09-16 10:18:48,363 [smrtpipe.status execute 620] Process id 19071
[INFO] 2014-09-16 10:18:54,374 [smrtpipe.status refreshTargets 419] Starting task://016438/P_Fetch/toFofn
[INFO] 2014-09-16 10:18:54,408 [smrtpipe.status refreshTargets 407] task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2014-09-16 10:18:54,408 [smrtpipe.status refreshTargets 409] Workflow Completion Status 1/9 in ( . 11%) tasks completed.
[INFO] 2014-09-16 10:18:59,426 [smrtpipe.status refreshTargets 419] Starting task://016438/P_Fetch/overviewRpt
[INFO] 2014-09-16 10:18:59,427 [smrtpipe.status refreshTargets 419] Starting task://016438/P_Barcode/labelZMWs
[INFO] 2014-09-16 10:18:59,428 [smrtpipe.status refreshTargets 419] Starting task://016438/P_Fetch/getChemistry
[INFO] 2014-09-16 10:18:59,428 [smrtpipe.status refreshTargets 419] Starting task://016438/P_Fetch/adapterRpt
[INFO] 2014-09-16 10:19:01,035 [smrtpipe.status refreshTargets 407] task P_Fetch.getChemistry successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 3 slots.
[INFO] 2014-09-16 10:19:01,035 [smrtpipe.status refreshTargets 409] Workflow Completion Status 2/9 in ( .. 22%) tasks completed.
[ERROR] 2014-09-16 10:19:01,036 [smrtpipe.status refreshTargets 413] *** Failed task task://016438/P_Barcode/labelZMWs
[INFO] 2014-09-16 10:19:02,611 [smrtpipe.status refreshTargets 407] task P_Fetch.overviewRpt successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 2 slots.
[INFO] 2014-09-16 10:19:02,612 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/9 in ( ... 33%) tasks completed.
[ERROR] 2014-09-16 10:19:02,613 [smrtpipe.status refreshTargets 413] *** Failed task task://016438/P_Fetch/adapterRpt
[INFO] 2014-09-16 10:19:02,615 [smrtpipe.status execute 627] task adapterRpt FAILED 
[ERROR] 2014-09-16 10:19:03,098 [pbpy.smrtpipe.SmrtPipeMain run 581] SmrtExit task://016438/P_Fetch/adapterRpt Failed
Traceback (most recent call last):
File "/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/lib/python2.7/pbpy-0.1-py2.7.egg/pbpy/smrtpipe/SmrtPipeMain.py", line 544, in run
self._runTasks(pModules)
File "/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/lib/python2.7/pbpy-0.1-py2.7.egg/pbpy/smrtpipe/SmrtPipeMain.py", line 276, in _runTasks
workflow.execute()
File "/opt/smartanalysis-2.1/smrtanalysis/install/smrtanalysis-2.1.1.128549/analysis/lib/python2.7/pbpy-0.1-py2.7.egg/pbpy/smrtpipe/engine/SmrtPipeWorkflow.py", line 635, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016438/P_Fetch/adapterRpt Failed
[ERROR] 2014-09-16 10:19:03,105 [pbpy.smrtpipe.SmrtPipeMain exit 667] SmrtExit task://016438/P_Fetch/adapterRpt Failed
[INFO] 2014-09-16 10:19:03,106 [pbpy.smrtpipe.SmrtPipeMain exit 669] Beginning exit process
[INFO] 2014-09-16 10:19:03,106 [pbpy.smrtpipe.SmrtPipeMain shutdown 690] beginning Shutdown Process
[INFO] 2014-09-16 10:19:03,106 [pbpy.smrtpipe.SmrtPipeMain _generate_final_report 620] Writing final TOC page with error message : SmrtExit task://016438/P_Fetch/adapterRpt Failed
[INFO] 2014-09-16 10:19:03,865 [pbpy.smrtpipe.SmrtPipeMain shutdown 725] Completed shutdown gracefully

**Comment by zusman** [comment]
Until now, My smrt v2.3 was running fine. But now it is throwing same error for same analysis.
I deleted all 016 files because it said the job id existed. But the issue remains. 
Somethings appears to happen at this step and the program crahes[ERROR] 2014-09-16 10:19:01,036 [smrtpipe.status refreshTargets 413] *** Failed task task://016438/P_Barcode/labelZMWs
[INFO] 2014-09-16 10:19:02,611 [smrtpipe.status refreshTargets 407] task P_Fetch.overviewRpt successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 2 slots.
[INFO] 2014-09-16 10:19:02,612 [smrtpipe.status refreshTargets 409] Workflow Completion Status 3/9 in ( ... 33%) tasks completed.
[ERROR] 2014-09-16 10:19:02,613 [smrtpipe.status refreshTargets 413] *** Failed task task://016438/P_Fetch/adapterRpt
[INFO] 2014-09-16 10:19:02,615 [smrtpipe.status execute 627] task adapterRpt FAILED
[ERROR] 2014-09-16 10:19:03,098 [pbpy.smrtpipe.SmrtPipeMain run 581] SmrtExit task://016438/P_Fetch/adapterRpt Failed

should i restart or is there any way i can refresh smrt services>??
