### ISSUE TITLE
PreAssemblerDagcon/hgapAlignForCorrection failed

### ISSUE THREAD

**Issue by xfzhao** [PacificBiosciences/SMRT-Analysis#142]
I used E-coli sample data, PreAssemblerDagcon/hgapAlignForCorrection failed as following. 

I check the log of jobs/016/016447/log/P_PreAssemblerDagco/hgapAlignForCorrection_006of006.stdout,  the message is:

---Could not open FASTA file /home-2/opt/smrtanalysis/userdata/jobs/016/016447/filtered_longreads.chunk006of006.fasta

I did not find this fasta file either.

-------------------------------------------------

the SMRT log:

[INFO] 2014-10-22 18:38:19,041 [smrtpipe.status refreshTargets 409] Workflow Completion Status 8/66 in ( . 12%) tasks completed.
[INFO] 2014-10-22 18:38:24,047 [smrtpipe.status refreshTargets 419] Starting task://016447/P_Filter/subreadSummary
[INFO] 2014-10-22 18:38:35,226 [smrtpipe.status refreshTargets 407] task P_Filter.filter.summary.Gather successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 4 slots.
[INFO] 2014-10-22 18:38:35,227 [smrtpipe.status refreshTargets 409] Workflow Completion Status 9/66 in ( . 13%) tasks completed.
[INFO] 2014-10-22 18:38:40,234 [smrtpipe.status refreshTargets 419] Starting task://016447/P_FilterReports/statsRpt
[INFO] 2014-10-22 18:38:40,234 [smrtpipe.status refreshTargets 419] Starting task://016447/P_FilterReports/loadingRpt
[INFO] 2014-10-22 18:38:56,535 [smrtpipe.status refreshTargets 407] task P_FilterReports.loadingRpt successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 5 slots.
[INFO] 2014-10-22 18:38:56,535 [smrtpipe.status refreshTargets 409] Workflow Completion Status 10/66 in ( . 15%) tasks completed.
[INFO] 2014-10-22 18:39:02,727 [smrtpipe.status refreshTargets 407] task P_FilterReports.statsRpt successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 4 slots.
[INFO] 2014-10-22 18:39:02,727 [smrtpipe.status refreshTargets 409] Workflow Completion Status 11/66 in ( . 16%) tasks completed.
[INFO] 2014-10-22 18:39:17,759 [smrtpipe.status refreshTargets 407] task P_Filter.subreads_003of003 successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 3 slots.
[INFO] 2014-10-22 18:39:17,759 [smrtpipe.status refreshTargets 409] Workflow Completion Status 12/66 in ( . 18%) tasks completed.
[INFO] 2014-10-22 18:39:24,189 [smrtpipe.status refreshTargets 407] task P_Filter.subreads_001of003 successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2014-10-22 18:39:24,189 [smrtpipe.status refreshTargets 409] Workflow Completion Status 13/66 in ( . 19%) tasks completed.
[INFO] 2014-10-22 18:39:34,227 [smrtpipe.status refreshTargets 407] task P_Filter.subreads_002of003 successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 1 slots.
[INFO] 2014-10-22 18:39:34,228 [smrtpipe.status refreshTargets 409] Workflow Completion Status 14/66 in ( .. 21%) tasks completed.
[INFO] 2014-10-22 18:39:35,764 [smrtpipe.status refreshTargets 407] task P_Filter.subreadSummary successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2014-10-22 18:39:35,764 [smrtpipe.status refreshTargets 409] Workflow Completion Status 15/66 in ( .. 22%) tasks completed.
[INFO] 2014-10-22 18:39:40,782 [smrtpipe.status refreshTargets 419] Starting task://016447/P_FilterReports/subreadRpt
[INFO] 2014-10-22 18:39:40,783 [smrtpipe.status refreshTargets 419] Starting task://016447/P_Filter/subreads.subreads.Gather
[INFO] 2014-10-22 18:39:40,783 [smrtpipe.status refreshTargets 419] Starting task://016447/P_Filter/subreads.subreadFastq.Gather
[INFO] 2014-10-22 18:39:52,343 [smrtpipe.status refreshTargets 407] task P_Filter.subreads.subreadFastq.Gather successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2014-10-22 18:39:52,343 [smrtpipe.status refreshTargets 409] Workflow Completion Status 16/66 in ( .. 24%) tasks completed.
[INFO] 2014-10-22 18:39:53,898 [smrtpipe.status refreshTargets 407] task P_Filter.subreads.subreads.Gather successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 1 slots.
[INFO] 2014-10-22 18:39:53,898 [smrtpipe.status refreshTargets 409] Workflow Completion Status 17/66 in ( .. 25%) tasks completed.
[INFO] 2014-10-22 18:39:55,410 [smrtpipe.status refreshTargets 407] task P_FilterReports.subreadRpt successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2014-10-22 18:39:55,411 [smrtpipe.status refreshTargets 409] Workflow Completion Status 18/66 in ( .. 27%) tasks completed.
[INFO] 2014-10-22 18:40:00,418 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/filterLongReadsByLength
[INFO] 2014-10-22 18:40:20,466 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.filterLongReadsByLength successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2014-10-22 18:40:20,466 [smrtpipe.status refreshTargets 409] Workflow Completion Status 19/66 in ( .. 28%) tasks completed.
[INFO] 2014-10-22 18:40:26,694 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection.target.Scatter
[INFO] 2014-10-22 18:40:41,738 [smrtpipe.status refreshTargets 407] task P_PreAssemblerDagcon.hgapAlignForCorrection.target.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2014-10-22 18:40:41,738 [smrtpipe.status refreshTargets 409] Workflow Completion Status 20/66 in ( ... 30%) tasks completed.
[INFO] 2014-10-22 18:40:46,760 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006
[INFO] 2014-10-22 18:40:46,760 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_002of006
[INFO] 2014-10-22 18:40:46,761 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006
[INFO] 2014-10-22 18:40:46,761 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006
[INFO] 2014-10-22 18:40:46,762 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006
[INFO] 2014-10-22 18:40:46,762 [smrtpipe.status refreshTargets 419] Starting task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006
[ERROR] 2014-10-22 18:42:23,123 [smrtpipe.status refreshTargets 413] *** Failed task task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006
[INFO] 2014-10-22 18:49:55,724 [smrtpipe.status execute 627] Found 5 failed tasks.
[INFO] 2014-10-22 18:49:55,724 [smrtpipe.status execute 629] task hgapAlignForCorrection_001of006 FAILED 
[INFO] 2014-10-22 18:49:55,725 [smrtpipe.status execute 629] task hgapAlignForCorrection_004of006 FAILED 
[INFO] 2014-10-22 18:49:55,725 [smrtpipe.status execute 629] task hgapAlignForCorrection_003of006 FAILED 
[INFO] 2014-10-22 18:49:55,726 [smrtpipe.status execute 629] task hgapAlignForCorrection_005of006 FAILED 
[INFO] 2014-10-22 18:49:55,727 [smrtpipe.status execute 629] task hgapAlignForCorrection_006of006 FAILED 
[ERROR] 2014-10-22 18:49:57,296 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006 Failed
Traceback (most recent call last):
File "/home-2/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
self._runTasks(pModules)
File "/home-2/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
workflow.execute()
File "/home-2/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
raise SmrtExit(str(e))
SmrtExit: SmrtExit task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006 Failed
[ERROR] 2014-10-22 18:49:57,297 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006 Failed
[INFO] 2014-10-22 18:49:57,297 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process
[INFO] 2014-10-22 18:49:57,297 [SMRTpipe.SmrtPipeMain shutdown 716] beginning Shutdown Process
[INFO] 2014-10-22 18:49:57,297 [SMRTpipe.SmrtPipeMain _generate_final_report 651] Writing final TOC page with error message : SmrtExit task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006 Failed
[INFO] 2014-10-22 18:49:58,068 [SMRTpipe.SmrtPipeMain shutdown 752] Completed shutdown gracefully
[INFO] 2014-10-22 18:49:58,068 [SMRTpipe.SmrtPipeMain exit 702] Sending message Exiting smrtpipe last error: SmrtExit task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006 Failed
[INFO] 2014-10-22 18:49:58,069 [smrtpipe.status failed 104] Sending Job 016447 failed message 'Exiting smrtpipe last error: SmrtExit task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_001of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_004of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_003of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_005of006 Failed task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006 Failed' to url http://129.186.142.93:8080/smrtportal/api/jobs/016447/status
[INFO] 2014-10-22 18:49:58,095 [SMRTpipe.SmrtPipeMain run 641] completed SmrtPipeMain.run with exit code -1
[INFO] 2014-10-22 18:49:58,095 [root main 335] Failed smrtpipe version v1.87.139483 with exit code -1 in 773.02 seconds (12.88 minutes)

**Comment by pb-jlandolin** [comment]
Maybe it failed further upstream?  We can generally debug all problems with the non-debug log files.

From your snippet, all we see is this:

```
[ERROR] 2014-10-22 18:42:23,123 [smrtpipe.status refreshTargets 413] *** Failed task task://016447/P_PreAssemblerDagcon/hgapAlignForCorrection_006of006
```

But the log is much longer.  There are some very basic things we would like to know in order to even    begin to troubleshoot:

1.  How many SMRT Cells are you running?
2.  What version of SMRT Portal you are running?
3.  What HGAP protocol you are running with what parameters, and if your settings.xml is well formed?
