### ISSUE TITLE
Temporary files should be kept if a job fails

### ISSUE THREAD

**Issue by tolot27** [PacificBiosciences/SMRT-Analysis#144]
When ever a job fails, all temporary/intermediate files will be deleted, even if `DEBUG = True` in `smrtpipe.rc` is set.

It is hardly possible to find the cause of a job failure or debugging into it, if the files were removed.

Hence I suggest not removing these files, if a job fails.

**Comment by tolot27** [comment]
Why did you close this issue? Is it implemented as I suggested?

**Comment by pb-jlandolin** [comment]
We are re-vamping some of the pipeline code, so it is not implemented exactly as you state, but there will be some architectural changes to make it easier to troubleshoot.
