### ISSUE TITLE
RS_CeleraAssembler.1 on SMRT Portal v2.2

### ISSUE THREAD

**Issue by maunei** [PacificBiosciences/SMRT-Analysis#148]
I would like to try Illumina paired reads for hybrid correction of pacbio data and assembly using the protocol RS_CeleraAssembler.1 on SMRT Portal v2.2.

I see the software doesn't allow me to point to two separate illumina fastq files for reads 1 and 2.
In the Protocol Details window (for the Assembly) tab there is an input field that says:
FASTQ to Correct with* , here I pointed to the two illumina reads files separated by a comma but a message in red tells me 'File Does Not Exist', however if I use any of the reads separately, there is no problem in recognizing both files.
I am wondering if the correct and only way is to merge the two reads in one file and I am also wondering if I have to get rid off the Ns at the ends for the illumina data (where adapters have been masked).

I don't see very much documentation in the SMRT Portal. 

Can any one tell me what would be the correct way of using this protocol? from the SMRT portal v2.2 interface?

This protocol is no longer included in the new release 2.3 ... any reasons why?
Was there something wrong with the implementation?

https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Analysis-Release-Notes-v2.3.0
The RS_CeleraAssembler protocol is no longer included.

Thanks

**Comment by pb-jlandolin** [comment]
RS_CeleraAssembler is no longer included.  The run parameters must be very carefully changed as more data is included, so we could not accommodate adding many illumina fastq files. You can still run PacBioToCA, but you must edit your own .spec file:

http://www.cbcb.umd.edu/software/PBcR/index.html

https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/pacBioToCA
