### ISSUE TITLE
header is multiple times replicated in variants.gff

### ISSUE THREAD

**Issue by tolot27** [PacificBiosciences/SMRT-Analysis#149]
There seem to be a small issue with the variant caller. The resulting variants.gff contains the header many times, hence blown up unnecessarily. It is exactly `n` times replicated at wich `n` is the number of consensus chunks.
The only line which is different between each header set is the line starting with `##source-commandline`.

**Comment by pb-jlandolin** [comment]
Ok.  I don't have enough info to reproduce or look into this problem.  

1.  Are you running variant_caller.py on the command-line or through SMRT Portal?
2.  If through SMRT Portal, does this happen using the included lambda SMRT cell?

**Comment by tolot27** [comment]
I've just used the Resequencing workflow in SMRT Portal and downloaded the variants.gff.gz from there.
It cannot be reproduced with the lambda SMRT cell because the lambda phage genome is so small that only one mapping/consensus chunk is running. Also, there is no way to controll the number of chunks as it is possible with the HGAP.3 workflow.

To reproduce the described behaviour, use a larger genome (i. e. a bacterial genome of 4 MB) and more SMRT cells. I've tested it again with a bacillus genome and four SMRT cells and got three header replicates.

But with our fungal genome we got 67 replicates and I belive, doing your 54x human genome resequencing, you'll get thousands of header replicates in the variant.gff. Maybe you can just take a look in the data Jason Chin has already run.

Please reopen the issue and I'll answer in time in the future. ;-)
