### ISSUE TITLE
strange link behavior

### ISSUE THREAD

**Issue by Kunzol** [PacificBiosciences/SMRT-Analysis#155]
We just installed SMRTanalysis and after some tests which showed, that everything works well on our cluster, we wanted to add more cluster nodes. We just added them to the Gridengine and put everything in place. Unfortunately the jobs did not run.

Some debugging later, we realized, that while creating the job scripts, all pathes are "canonicalized", with "readlink". As we have different mount points on the nodes (don't ask why, this is not the point) all jobs contain the pathes which are only valid on the SMRTportal node.

Sure, I can find a "workaround" for this and mount it all in the same directories on the cluster node. 

But as a sysadmin I am wondering whats behind this behavior?
Why are the links "canonicalized" ? 

This behavior makes it hard to "archive" the jobs for documentation. It is hard to reproduce the results on a different environment.

**Comment by pb-jlandolin** [comment]
It's just something we had to do as customers have some really strange softlinking that would sometimes break the install....
