### ISSUE TITLE
Missing metadata.xml

### ISSUE THREAD

**Issue by bwkchee** [PacificBiosciences/SMRT-Analysis#158]
Is there a way to recreate a metadata.xml file? I have the 3 bax.h5 files and a single bas.h5 file and am trying to import the smrtcell into smrtportal for analysis.  Alternatively is there any way to export data from a SRA file so that it can be used in smrtportal for analysis?

**Comment by pb-jlandolin** [comment]
Unfortunately no. 

The SRA does not keep metadata.xml files or even provided bas/bax.h5 files.  We have been asking them to support these files for some time now. 

It is also not possible to hack the metadata.xml file.  I believe I have tried to copy the metadata.xml from another SMRT Cell, then manually edit the entries for the bax.h5 files, and while I was then able to import to SMRT Portal, subsequent analyses failed b/c some entries were inconsistent.  I don't know what they were.  

You might be able to hack it some more with more manual guessing and editing, but at that point it might be easier to just go to the data creator and ask for all the supporting files.
