### ISSUE TITLE
adapterRpt error

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/SMRT-Analysis#159]
Dear all and @pb-jlandolin,

Hi !

I try to run SMRT analysis 2.3 but got adapterRpt error.

####

[INFO] 2014-12-15 10:07:57,493 Workflow Completion Status 16/287 in (            5%) tasks completed.
[INFO] 2014-12-15 10:08:02,513 Starting task://Anonymous/P_Mapping/align_007of064
[ERROR] 2014-12-15 10:12:15,046 *** Failed task task://Anonymous/P_Fetch/adapterRpt
[INFO] 2014-12-15 13:30:12,912 Found 1 failed tasks.
[INFO] 2014-12-15 13:30:12,912 task adapterRpt FAILED 
Failed smrtpipe version v1.87.139483 with exit code -1 in 13735.67 seconds (228.93 minutes)
####

First I took a look into adapterRpt.log. But there's a simple error message below.

Second I checked input.chunk007of064 by h5debug. And my file looks good.

Is there anyway to run it?

My other species set of bax.h5 (p4c3 + P5c4 )  works good.

But for this 235 cell (p4c3 + P5c4 ) has error.

Won

#####h5debug
wyim@hnode /scratch/wyim/smrtpipe/kl $  h5debug /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/B06_7/Analysis_Results/m140907_005125_42160_c100681522550000001823142002221576_s1_p0.1.bax.h5 
Reading signature at address 0 (rel)
File Super Block...
File name (as opened):                             /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/B06_7/Analysis_Results/m140907_005125_42160_c100681522550000001823142002221576_s1_p0.1.bax.h5
File name (after resolving symlinks):              /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/B06_7/Analysis_Results/m140907_005125_42160_c100681522550000001823142002221576_s1_p0.1.bax.h5
File access flags                                  0x00000000
File open reference count:                         1
Address of super block:                            0 (abs)
Size of userblock:                                 0 bytes
Superblock version number:                         0
Free list version number:                          0
Root group symbol table entry version number:      0
Shared header version number:                      0
Size of file offsets (haddr_t type):               8 bytes
Size of file lengths (hsize_t type):               8 bytes
Symbol table leaf node 1/2 rank:                   4
Symbol table internal node 1/2 rank:               16
File status flags:                                 0x00
Superblock extension address:                      UNDEF (rel)
Shared object header message table address:        UNDEF (rel)
Shared object header message version number:       0
Number of shared object header message indexes:    0
Address of driver information block:               UNDEF (rel)
Root group symbol table entry:                     
   Name offset into private heap:                  0
   Object header address:                          96
   Cache info type:                                Symbol Table
   Cached entry information:                      
      B-tree address:                              136
      Heap address:                                680
wyim@hnode /scratch/wyim/smrtpipe/kl $ h5debug /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/H01_1/Analysis_Results/m140821_031834_42160_c100664432550000001823133312201400_s1_p0.3.bax.h5
Reading signature at address 0 (rel)
File Super Block...
File name (as opened):                             /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/H01_1/Analysis_Results/m140821_031834_42160_c100664432550000001823133312201400_s1_p0.3.bax.h5
File name (after resolving symlinks):              /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/H01_1/Analysis_Results/m140821_031834_42160_c100664432550000001823133312201400_s1_p0.3.bax.h5
File access flags                                  0x00000000
File open reference count:                         1
Address of super block:                            0 (abs)
Size of userblock:                                 0 bytes
Superblock version number:                         0
Free list version number:                          0
Root group symbol table entry version number:      0
Shared header version number:                      0
Size of file offsets (haddr_t type):               8 bytes
Size of file lengths (hsize_t type):               8 bytes
Symbol table leaf node 1/2 rank:                   4
Symbol table internal node 1/2 rank:               16
File status flags:                                 0x00
Superblock extension address:                      UNDEF (rel)
Shared object header message table address:        UNDEF (rel)
Shared object header message version number:       0
Number of shared object header message indexes:    0
Address of driver information block:               UNDEF (rel)
Root group symbol table entry:                     
   Name offset into private heap:                  0
   Object header address:                          96
   Cache info type:                                Symbol Table
   Cached entry information:                      
      B-tree address:                              136
      Heap address:                                680
wyim@hnode /scratch/wyim/smrtpipe/kl $ h5debug /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/F05_4/Analysis_Results/m140810_023642_42160_c100664332550000001823133312201437_s1_p0.2.bax.h5
Reading signature at address 0 (rel)
File Super Block...
File name (as opened):                             /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/F05_4/Analysis_Results/m140810_023642_42160_c100664332550000001823133312201437_s1_p0.2.bax.h5
File name (after resolving symlinks):              /home/wyim/scratch/smrtpipe/kl/source/Run_at_WSU/F05_4/Analysis_Results/m140810_023642_42160_c100664332550000001823133312201437_s1_p0.2.bax.h5
File access flags                                  0x00000000
File open reference count:                         1
Address of super block:                            0 (abs)
Size of userblock:                                 0 bytes
Superblock version number:                         0
Free list version number:                          0
Root group symbol table entry version number:      0
Shared header version number:                      0
Size of file offsets (haddr_t type):               8 bytes
Size of file lengths (hsize_t type):               8 bytes
Symbol table leaf node 1/2 rank:                   4
Symbol table internal node 1/2 rank:               16
File status flags:                                 0x00
Superblock extension address:                      UNDEF (rel)
Shared object header message table address:        UNDEF (rel)
Shared object header message version number:       0
Number of shared object header message indexes:    0
Address of driver information block:               UNDEF (rel)
Root group symbol table entry:                     
   Name offset into private heap:                  0
   Object header address:                          96
   Cache info type:                                Symbol Table
   Cached entry information:                      
      B-tree address:                              136
      Heap address:                                680

####
cat log/P_Fetch/adapterRpt.log 

#!/bin/bash
# Setting up SMRTpipe environment
echo "Setting up ENV on $(uname -n)" for task adapterRpt

SEYMOUR_HOME=/home/wyim/scratch/smrtpipe/smrtanalysis/current
source $SEYMOUR_HOME/etc/setup.sh

# Create the local TMP dir if it doesn't exist
tmp_dir=$(readlink -m "/scratch/wyim/smrtpipe/smrtanalysis/tmpdir")
if [ ! -e "$tmp_dir" ]; then
   stat=0
   mkdir -p $tmp_dir || stat=$?
   if [[ $stat -ne 0 ]]; then
       echo "SMRTpipe Unable to create TMP dir '/scratch/wyim/smrtpipe/smrtanalysis/tmpdir' on $(uname -n)" 1>&2
       exit 1
   else
       echo "successfully created or found TMP dir '/scratch/wyim/smrtpipe/smrtanalysis/tmpdir'"
   fi
elif [[ ! -d "$tmp_dir" ]]; then
   echo "SMRTpipe TMP /scratch/wyim/smrtpipe/smrtanalysis/tmpdir must be a directory on $(uname -n)" 1>&2
   exit 1
fi

########### TASK metadata #############
# Task            : adapterRpt
# Module          : P_Fetch
# Module Version  : 2.4.139483
# TaskType        : None
# URL             : task://Anonymous/P_Fetch/adapterRpt
# createdAt       : 2014-12-15 09:42:56.047141
# createdAt (UTC) : 2014-12-15 17:42:56.047165
# ncmds           : 2
# LogPath         : /scratch/wyim/smrtpipe/kl/log/P_Fetch/adapterRpt.log
# Script Path     : /scratch/wyim/smrtpipe/kl/workflow/P_Fetch/adapterRpt.sh

# Input       : /scratch/wyim/smrtpipe/kl/input.fofn
# Output      : /scratch/wyim/smrtpipe/kl/results/filter_reports_adapters.json
#
########### END TASK metadata #############

cd /scratch/wyim/smrtpipe/kl/log/P_Fetch
# Writing to log file
cat /scratch/wyim/smrtpipe/kl/workflow/P_Fetch/adapterRpt.sh >> /scratch/wyim/smrtpipe/kl/log/P_Fetch/adapterRpt.log;

echo "Running task://Anonymous/P_Fetch/adapterRpt on $(uname -a)"

echo "Started on $(date -u)"
echo 'Validating existence of Input Files'
if [ -e /scratch/wyim/smrtpipe/kl/input.fofn ]
then
echo 'Successfully found /scratch/wyim/smrtpipe/kl/input.fofn'
else
echo 'WARNING: Unable to find necessary input file, or dir /scratch/wyim/smrtpipe/kl/input.fofn.'
fi
echo 'Successfully validated input files'

# Task adapterRpt commands:

# Completed writing Task adapterRpt commands

# Task 1
pbreport.py adapter /scratch/wyim/smrtpipe/kl/results filter_reports_adapters.json /scratch/wyim/smrtpipe/kl/input.fofn || exit $?
echo "Task 1 completed at $(date)"
# Task 2
smrtreporter -basedir /scratch/wyim/smrtpipe/kl/results -headinclude /scratch/wyim/smrtpipe/kl/results/.martin_header.html --html -o filter_reports_adapters.html -rules /scratch/wyim/smrtpipe/kl/results/.rules_filter_reports_adapters.xml || exit $?
echo "Task 2 completed at $(date)"

rcode=$?
echo "Finished on $(date -u)"
echo "Task adapterRpt with nproc 1 with exit code ${rcode}."
exit ${rcode}# Writing stdout and stderr from Popen:
Setting up ENV on compute-4-2.local for task adapterRpt
Running task://Anonymous/P_Fetch/adapterRpt on Linux compute-4-2.local 2.6.32-431.5.1.el6.x86_64 #1 SMP Wed Feb 12 00:41:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Started on Mon Dec 15 17:43:46 UTC 2014
Validating existence of Input Files
Successfully found /scratch/wyim/smrtpipe/kl/input.fofn
Successfully validated input files
Traceback (most recent call last):
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbsystem/common/cmdline/core.py", line 19, in args_executer
    return_code = args.func(args)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 350, in args_runner
    return make_adapter_report(args.fofn, args.report, args.output, args.dpi, args.dumpdata)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 56, in make_adapter_report
    rpt = to_report_streaming(bas_files, output_dir, dpi)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 210, in to_report_streaming
    trimmed_histogram, untrimmed_histogram = _create_histograms(bas_files)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 196, in _create_histograms
    applier(bas_files, funcs)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 181, in applier
    func(it)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 159, in calc_untrimmed_adapter_histogram
    for idx, zmw in enumerate(_get_zmw_records([bas_file], 'allSequencingZmws')):
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/adapter.py", line 147, in _get_zmw_records
    b = BasH5Reader(bas_file)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 765, in __init__
    self._parts = [ BaxH5Reader(self.filename) ]
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 437, in __init__
    self._loadRegions(self.file)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 462, in _loadRegions
    fh["/PulseData/Regions"].value)
  File "/home/wyim/scratch/smrtpipe/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:2946)
KeyError: "unable to open object (Symbol table: Can't open object)"

**Comment by pb-jlandolin** [comment]
Closing this issue as we cannot support an install without functional SMRT Portal.  There is no way to generate a functional settings.xml file.  We have worked with this user elsewhere and recommended using the Amazon EC2 instance to generate valid settings.xml files or to run their data.
