### ISSUE TITLE
SMRTview does not display Contig sequence consistently

### ISSUE THREAD

**Issue by ragowthaman** [PacificBiosciences/SMRT-Analysis#165]
Hi,
I have been trying to view base modification data in smrtview. The genome sequence in the detailed panel displays bases for some contigs and not for others. I placed fasta file (.fai index and .sa indexed files as well) in the sequence folder, and are corrected referenced in reference.xml file. 

It appears most (not all) the small contigs (~ <2000) have the contig sequences displayed, but, longer sequences are not. But, its not consistent. And once I click many of the longer sequence, the shorter sequences, even the one showed sequence before would stop showing them.

Of course, I am zooming into nt level to check.

Couple possibilities.
1) I do NOT have xxx.fasta.index file (not sure where to get the indexer software) to create one. [.fai and .sa files are in place]

2) The fasta file I used had long headers with pipes and spaces in them. It looks like smrtpipe tools truncated them at certain length. (an example below). That could mess this up. But, again, i do NOT see any consistent pattern of naming between them.

```
<contig length="1394517" id="ref001349" displayName="LtaP31 | organism=Leishmania_tarentolae_Parrot-TarII | version=2">
            <digest type="md5">48db5f0e589a6b93fd2ceb03aaf2e48e</digest>
            <header>LtaP31 | organism=Leishmania_tarentolae_Parrot-TarII | version=2011-06-22 | length=1394517 | SO=chromosome</header>
        </contig>
```

Any help is appreciated.

**Comment by pb-jlandolin** [comment]
If you "placed the fasta, fai, sa" files manually, we cannot guarantee that this will work.  You need to import the contigs using SMRT Portal, and launch SMRT View after running an RS_Resequencing job.

**Comment by ragowthaman** [comment]
Thanks. The alignment was done elsewhere (@pacbio, CA), and we got only the alignment files. Is there anyother way we can resolve this?

**Comment by pb-jlandolin** [comment]
Ah, I see.  I'm not sure how to hack this to get it to work then.  This is and why there is a "golden path" through SMRT Portal to get these things to work.  Any other method just introduces headaches.  It is much better to spend some time to do things the supported way first and then see how to deviate from there.

**Comment by khaikhai** [comment]
Marcos M. might have some suggestions. There may have been some changes in
how the stand-alone SMRTView works with recent files.

Best,
Khai
