### ISSUE TITLE
SMRTanalysis does not display graphs for mapping

### ISSUE THREAD

**Issue by sagarutturkar** [PacificBiosciences/SMRT-Analysis#166]
Hi,

I have SMRTportal version 2.2 installed. I am running HGAP_3 protocol with my data which completes without any problems. However, somehow when i click on Mapping section, All graphs appear to be empty. All other graphs, e.g. adapters, subread filtering, coverage, corrections are there. But mapping graphs appear empty.

I tried this workflow with lambda test genome and it generates mapping graph correctly. I therefore recognize something wrong with data files, and reloaded data from backup. Still having same issue.

One thing I noticed is in report, the correct graphs mention SMRTcell IDs as "m130....." while failed mapping section mentiones IDs as "XSBOR...". I am not sure where it is picking wrong name/IDs and workaround for this.

This is very weired, but very frustrating to figure out.
Log_file, PDF_report and metadata.xml files are shared at link: https://www.dropbox.com/s/st2u7rq0aut1ok1/SMRT_bug.zip?dl=0

Any help is much appreciated.

Thanks
Sagar
Thanks
Sagar

**Comment by pb-jlandolin** [comment]
Woa, that is really strange.  It looks like someone re-named the metadata file to `XSBOR_20130726_RS42150_PL100036291-1_C02.metadata.xml`, when we are expecting "m130..." Can you re-name the file back to the expected value and re-import?

**Comment by sagarutturkar** [comment]
This is how my directory structure looks like.

Data looks like:
DSM10061
XSBOR_20130726_RS42150_PL100036291-1_C02.metadata.xml
XSBOR_20130726_RS42150_PL100036291-1_D02.metadata.xml

Analysis_Results
XSBOR_20130726_RS42150_PL100036291-1_C02.1.bas.h5
XSBOR_20130726_RS42150_PL100036291-1_D02.1.bas.h5
XSBOR_20130726_RS42150_PL100036291-1_C02.1.1.bax.h5
XSBOR_20130726_RS42150_PL100036291-1_C02.1.2.bax.h5
XSBOR_20130726_RS42150_PL100036291-1_C02.1.3.bax.h5
XSBOR_20130726_RS42150_PL100036291-1_D02.1.1.bax.h5
XSBOR_20130726_RS42150_PL100036291-1_D02.1.2.bax.h5
XSBOR_20130726_RS42150_PL100036291-1_D02.1.3.bax.h5

Since All files start with XSBOR, the name "m130...." picked from somewhere else. I do have the sam/bam files since job finished succesfully.

I have ran this data previously with same filenames and it worked fine. Previous run report is shared at:
https://www.dropbox.com/s/ubt6u8xwbe43f94/DSM10061_HGAP_Report.pdf?dl=0

If you still think renaming is necessary, I will try it.

Is there any other way to get these graphs (may be through command line tools) or some workaround for this?

Thanks
Sagar

**Comment by sagarutturkar** [comment]
Well, I did this. renamed all the files (metada.xml, bas.h5, ) with "m130...." as needed. But somehow, no luck.
The mapping report shows different names now, but still no graphs appear.

New report shared at: https://www.dropbox.com/s/6h2l0cjix0fwfb0/Motif_Analysis_try2.pdf?dl=0

Hopefully someone can help with this. I need this concordance graph to include in a publication and this simple step is somehow turning out to be a very frustrating one.

**Comment by sagarutturkar** [comment]
Hi also tried with different dataset and same problem persist. Please let me know if you need any more information or found any workaround for this.

**Comment by pb-jlandolin** [comment]
Hi Sagar, 

The files are still named incorrectly.  See this article for an example of valid filenames (https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Cannot-import-new-SMRT-Cells)

1.  You need `s1_p0` before the suffix.  
2.  You need to separate the two SMRT Cells into different directories.

I have renamed the files to the following, and was able to generate the mapping reports. 

```
├── DSM10061_Modified_1
│   ├── Analysis_Results
│   │   ├── m130727_021351_42150_c100538232550000001823086511101336_s1_p0.1.bax.h5
│   │   ├── m130727_021351_42150_c100538232550000001823086511101336_s1_p0.2.bax.h5
│   │   ├── m130727_021351_42150_c100538232550000001823086511101336_s1_p0.3.bax.h5
│   │   ├── m130727_021351_42150_c100538232550000001823086511101336_s1_p0.bas.h5
│   └── m130727_021351_42150_c100538232550000001823086511101336_s1_p0.metadata.xml


The files you sent me looked like the following, which is incorrect:
```
├── DSM10061_Modified_2
│   ├── Analysis_Results
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.1.1.bax.h5
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.1.2.bax.h5
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.1.3.bax.h5
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.1.bas.h5
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.ccs.fastq
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.ccs_stats.txt
│   │   ├── m130727_043304_42150_c100538232550000001823086511101337.fastq
│   │   └── m130727_043304_42150_c100538232550000001823086511101337_stats.txt
│   ├── m130727_043304_42150_c100538232550000001823086511101337.metadata.xml
```

**Comment by sagarutturkar** [comment]
Hello,

I have upgraded our system to SMRT analysis version 2.3.0. I am trying to import my previous data into new version but unable to do so. I am not sure if this is regarding naming convenstion or something else. My current directory structure looks like this:

/illumina/Projects/temp/Paradoxum/
|-- Paradoxum_SMRT1
|   |-- Analysis_Results
|   |   |-- m140214_031906_42150_c100628242550000001823104408061455_s1_p0.1.bax.h5
|   |   |-- m140214_031906_42150_c100628242550000001823104408061455_s1_p0.2.bax.h5
|   |   |-- m140214_031906_42150_c100628242550000001823104408061455_s1_p0.3.bax.h5
|   |   |-- m140214_031906_42150_c100628242550000001823104408061455_s1_p0.bas.h5
|   |   |-- XSBOR_20140212_RS42150_PL100042926-1_B05-1.fastq
|   |   `-- XSBOR_20140212_RS42150_PL100042926-1_B05-1_stats.txt
|   `-- m140214_031906_42150_c100628242550000001823104408061455_s1_p0.metadata.xml

`-- Paradoxum_SMRT2_3
    |-- Analysis_Results
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1.1.1.bax.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1.1.2.bax.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1.1.3.bax.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1.1.bas.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1.fastq
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1_stats.txt
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-2.1.1.bax.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-2.1.2.bax.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-2.1.3.bax.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-2.1.bas.h5
    |   |-- XSBOR_20140314_RS42150_PL100042926-1_G08-2.fastq
    |   `-- XSBOR_20140314_RS42150_PL100042926-1_G08-2_stats.txt
    |-- XSBOR_20140314_RS42150_PL100042926-1_G08-1.1.metadata.xml
    `-- XSBOR_20140314_RS42150_PL100042926-1_G08-2.1.metadata.xml

 First, I tried to import the data with original naming scheme as we received from the instrument vendor (i.e. XSBOR.....). The SMRT_cell data "Paradoxum_SMRT2_3" is correctly imported into SMRTAnalysis but not the  "Paradoxum_SMRT1". Therefore I changed the file-names in "Paradoxum_SMRT1" as shown above. The tag "m140214_031906_42150_c100628242550000001823104408061455_s1_p0" was derived from the fastq file in same SMRT cell and with command "head XSBOR_20140212_RS42150_PL100042926-1_B05-1.fastq" which outputs:

@m140214_031906_42150_c100628242550000001823104408061455_s1_p0/20/0_11014
AGGAACCAGCGAGTATACTCCGCGCACAGGAGCACTGATCACGCCGGTGACGACTCAACCCCCGCACCCCTTATACAGGAGACAGAATATGTCATTACTGGACTGGAGTCAATAGGTCTGTAGCTACGCACAAAGGGAAGAGATGATGGATTATGTGTTGTGGCAG

Please help with this.

Thanks
Sagar
