### ISSUE TITLE
Cannot Enable Transport Layer Security

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/SMRT-Analysis#169]
I was trying to Enable Transport Layer Security, I applied the change but when I refreshed the page, the option became unchecked. Consequently, I couldn't make email notification work on SMRT portal. Is there a way to manually change the setting?

```
SMRT Analysis
smrtanalysis_2.3.0.140936.p0.0

Components
Daemon 2.3.0.139497
SMRTpipe 2.3.0.139497
SMRT Portal 2.3.0.140893
SMRT View 2.3.0.140836
```

**Comment by jkaralius** [comment]
Hi yunfeiguo,

The SMRT Portal UI has a bug here.  The TLS checkbox will always show unchecked regardless of actual value in smrtportal DB.

To confirm your actual TLS settings, use dbadmin to query the smrtportal DB:
```
$SMRT_ROOT/current/admin/bin/dbadmin --command 'SELECT name,valueStr FROM smrtportal.GlobalSetting WHERE name = "smtp-starttls-enable";'
```

To enable TLS in the PortalUI, check the box, then click Apply.  The db command above should output:

```
+----------------------+----------+
| name                 | valueStr |
+----------------------+----------+
| smtp-starttls-enable | true     |
+----------------------+----------+
```
To disable TLS in the SMRT Portal UI, first check the box to enable the Apply button, then uncheck and click Apply.  The db command above should then output:

```
+----------------------+----------+
| name                 | valueStr |
+----------------------+----------+
| smtp-starttls-enable | false     |
+----------------------+----------+
```

Best,
Joey
