### ISSUE TITLE
reference genome validation failed

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/SMRT-Analysis#170]
Dear PacBio developers,

I was trying to import hg19 and hg38 human genomes into SMRT portal, however validation always failed. I cannot get email notification so I am not sure what is error message yet. Could you please help me? The genomes are the standard references for human.

Thanks!

```
ftp://ftp.ncbi.nlm.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz
ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_full_analysis_set.fna.gz
```

**Comment by yunfeiguo** [comment]
I found a similar issue occurred before, do I have to wrap the FASTA file?

**Comment by mjhsieh** [comment]
It's not likely the same case. From the error log uploading human_g1k_v37.fasta:
<pre>':' character is not allowed in the header. Terminating</pre>

You can try ```sed -i -e 's@:@_@g' human_g1k_v37.fasta``` command to convert all ':' in the fasta headers to '_'.

**Comment by yunfeiguo** [comment]
Thanks! I'm trying with converted fasta.
