### ISSUE TITLE
smrt 2.3 error help me solve this error

### ISSUE THREAD

**Issue by madhubioinfo** [PacificBiosciences/SMRT-Analysis#171]
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/smrtpipe.py", line 12, in <module>
    from SMRTpipe.SmrtPipeMain import SmrtPipeMain, _sanityCheck
ImportError: No module named SMRTpipe.SmrtPipeMain

**Comment by jkaralius** [comment]
Hi madhubioinfo,

Make sure you are properly sourcing the SMRT Analysis environment, prior to executing `smrtpipe.py`.

I can reproduce your error by just running `smrtpipe.py` in my standard user environment:
```
jkaralius@badger:~$ SMRT_ROOT=/home/smrtanalysis/23beta/smrtanalysis/
jkaralius@badger:~$ $SMRT_ROOT/current/analysis/bin/smrtpipe.py --version
Traceback (most recent call last):
  File "/home/smrtanalysis/23beta/smrtanalysis//current/analysis/bin/smrtpipe.py", line 11, in <module>
    from SMRTpipe.SmrtPipeMain import SmrtPipeMain, _sanityCheck
ImportError: No module named SMRTpipe.SmrtPipeMain
```

But when I set up the SMRT Analysis environment first, I can execute `smrtpipe.py` without failure:
```
jkaralius@badger:~$ source $SMRT_ROOT/current/etc/setup.sh && $SMRT_ROOT/current/analysis/bin/smrtpipe.py --version

[WARNING] sourcing etc/setup.sh removes all environment variables except USER,
          LOGNAME, PWD, TERM, TERMCAP, HOME, WORKSPACE, MPLCONFIGDIR and all
          SMRT_* variables.

[WARNING] please see the SMRT Analysis release notes for more details.

smrtpipe.py v1.87.139483
(smrtanalysis-2.3.0) jkaralius@badger:~$
```

For more information on good practice SMRT Pipe command-line usage, please refer to:
https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Pipe-Reference-Guide-v2.3.0#-command-line-usage

Best,
Joey
