### ISSUE TITLE
Controlling "ConsensusTools.sh CircularConsensus .."

### ISSUE THREAD

**Issue by markrobinsonuzh** [PacificBiosciences/SMRT-Analysis#172]
I'm hoping someone can help me understand how the tool to extract reads of insert works.

I run a command like this from the command line:

ConsensusTools.sh CircularConsensus --minFullPasses=0 --minPredictedAccuracy=75 --minLength=500 --numThreads=15 --fofn=input.fofn -output=/seq/my_PacBio/CCS --logFile=/seq/my_PacBio/CCS/log.txt -parameters=/home/Shared/PacBio/smrt_2.3.0/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09

When I receive the data, I get bax.h5 files and subreads.fast[aq] .. and I want to understand why sequences drop out when I compare the subreads I get to the CCS/Reads of Insert that get extracted from the above command.

For example, if I look at the subreads (small snippet below), I see ZMW=1710 (a 26kb read!) in the subreads, but not in the CCS.  Why?

Thanks in advance for your insight,
Mark

mark:/seq/my_PacBio$ grep m all_subreads.fq | head -n 20
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/388/0_9396 RQ=0.842
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/425/0_19735 RQ=0.839
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/689/0_32756 RQ=0.821
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/927/0_104 RQ=0.851
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1062/0_11870 RQ=0.840
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1105/0_3333 RQ=0.878
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1339/0_154 RQ=0.875
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1472/0_2437 RQ=0.774
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1576/0_3106 RQ=0.823
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1646/0_161 RQ=0.846
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1687/0_851 RQ=0.750
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1710/0_26860 RQ=0.859
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1710/26902_31342 RQ=0.859
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1718/69_2372 RQ=0.828
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1718/2415_4631 RQ=0.828
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1780/0_1423 RQ=0.833
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1780/1465_1876 RQ=0.833
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1814/0_6165 RQ=0.761
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1822/162_8137 RQ=0.874
@m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1909/26_12515 RQ=0.819

mark:/seq/my_PacBio$ grep m CCS/m150113_185430_42243_c100751382550000001823169707081500_s1_p0.1.ccs.fasta | head -n 20
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/388/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/425/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/689/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1062/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1105/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1472/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1576/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1687/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1718/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1814/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1822/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/1909/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2088/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2143/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2179/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2184/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2187/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2191/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2316/ccs
>m150113_185430_42243_c100751382550000001823169707081500_s1_p0/2330/ccs

----
[WARNING] sourcing etc/setup.sh removes all environment variables except USER,
          LOGNAME, PWD, TERM, TERMCAP, HOME, WORKSPACE, MPLCONFIGDIR and all
          SMRT_* variables.

[WARNING] please see the SMRT Analysis release notes for more details.

ConsensusTools v2.3.0.140936 (c) 2014 Pacific Biosciences, Inc.
----

**Comment by evolvedmicrobe** [comment]
Hi Mark,

That particular ZMW apparently has only two subreads, one of length ~27 kb and another of length ~4 kb.  CCS is designed to take data from multiple passes over the same template and combine them into one high quality sequence.  By default, the CCS algorithm requires 2 full passes over a candidate template before it attempts to generate consensus, and in this case two passes were not available, likely causing this ZMW to not be emitted.  Typically more than 2X passes are needed to obtain very high quality (Q30) data. 

CCS can filter out a subread (and thus not report it) for a variety of reasons, including:

* An initial template of sufficient quality could not be generated from the subreads (that is, they were so noisy no consensus appeared)
* The read was below predicted accuracy thresholds
* The read appeared to come from 2 enyzmes polymerizing from 2 templates in the same ZMW
* No insert regions were found
* The template in between inserts was too short (<5 bp)
* The read appeared palindromic (designed to filter out reads with missed adapter calls)
* A rare event caused a programatic exception to be thrown while the read was being processed (will also generate an error message)

However, in this case it was the lack of full passes and the discrepancy between passes that likely caused the error.  You can confirm this by running it with the option:

    --minFullPasses=0

**Comment by evolvedmicrobe** [comment]
Just noticed you already had the minFullPasses=0 flag, next most likely candidate is that it was filtered by the predicted accuracy flag you used: 

    --minPredictedAccuracy=75

Which you could attempt to lower to verify.

**Comment by markrobinsonuzh** [comment]
Great, thanks for the answer.  It looks like it is indeed the 'minPredictedAccuracy' cutoff .. if I drop that number, it comes out in the CCS.fast[aq] file.  I had thought that this argument was related to RQ number (for my ZMW=1710, RQ=0.859), but it appears that is not the case.

Thanks, Mark
