### ISSUE TITLE
HGAP 2.3 error

### ISSUE THREAD

**Issue by madhubioinfo** [PacificBiosciences/SMRT-Analysis#173]
@mjhsieh when installing actually smrt writes in a lib area , in my machine the lib is only allowed for su users so, i have made it as a super user and installed it

**Comment by mjhsieh** [comment]
Which file is copied to the lib area? We would like to know about it.

**Comment by mjhsieh** [comment]
Seems to be a duplicate issue of #174

**Comment by madhubioinfo** [comment]
Now what can be can be done to work with the fastq subreads with AHA and
HGAP ? help me to fix this issue

*Mathu Malar C*
*Research Scholar at computational Biology and Genomics Lab,*
*CSIR - Indian Institute of Chemical biology,*
*kolkata-32*

**Comment by mjhsieh** [comment]
Perhaps ask your question at pacbio's Bioinformatics-Training project page.

**Comment by mjhsieh** [comment]
Or please contact regional regional PacBIo Field Apps Support people for research/experiment design.
