### ISSUE TITLE
Configure SMRT Portal to start at boot?

### ISSUE THREAD

**Issue by IndyMark** [PacificBiosciences/SMRT-Analysis#175]
Is there documentation on how to configure the SMRT Analysis services to automatically start on boot?  I'm using CentOS 6.

I know I need to run the following commands, and I'm assuming they need to run as the smrtanalysis user?

$SMRT_ROOT/admin/bin/smrtportald-initd start
$SMRT_ROOT/admin/bin/kodosd start   (not really sure what this one is)

**Comment by jkaralius** [comment]
Hi IndyMark,

By default, SMRT Analysis daemons do not start automatically at boot time. We have seen servers with multiple SMRT Analysis installations in different installation paths, resulting in init scripts starting tomcat servers for older or the wrong version.  This caused extra pain for users and sysadmins.  We leave it up to the admin to determine how to control the daemons.
 
If you wish, one way to do this, you can create symlinks in your `/etc/init.d` directory pointing to the scripts in `$SMRT_ROOT/admin/bin`.

```
$SMRT_ROOT=/path/to/smrt_root
sudo ln -sfn $SMRT_ROOT/admin/bin/smrtportald-initd /etc/init.d/smrtportald-initd
sudo ln -sfn $SMRT_ROOT/admin/bin/kodosd /etc/init.d/kodosd
```
Make sure there aren't existing tomcatd, kodosd or smrtportald-initd symlinks pointing to other places.

Kodos is the secondary auto-analysis daemon, which is only needs to be started if you have an RSII instrument.

Joey
