### ISSUE TITLE
pacbio assembly

### ISSUE THREAD

**Issue by madhubioinfo** [PacificBiosciences/SMRT-Analysis#176]
I have  pacbio long reads and previous version of illumina assembly of an fungal genome , i have tried ectools to correct my pacbio long reads by using my illumina contigs and after correcting i have generated the contigs from celera assembler and i would like to make the scaffold of that genome , how can i proceed further? either i dont have .h5 files or or either illumina read files i have only the filtered pacbio subreads in both fastq and fasta format and illumina contigs

**Comment by madhubioinfo** [comment]
Hello @mjhsieh actually am trying to do hybdrid assembly with aha  and as well as HGAP also , i tried running by using fasta files of pacbio subreads and fastq subreads i cannot do

For the HGAP assembly this is the params.xml but it worked well with the bax.h5 files, i dont have all the bax.h5 files i have fastq reads i want to use these files
        <value>reference</value>
    </param>
  </module>
  <module name="P_Mapping">
    <param name="maxHits">
        <value>10</value>
    </param>
    <param name="maxDivergence">
        <value>30</value>
    </param>
    <param name="placeRepeatsRandomly">
        <value>True</value>
    </param>
    <param name="pulseMetrics">
        <value>DeletionQV,IPD,InsertionQV,PulseWidth,QualityValue,MergeQV,SubstitutionQV,DeletionTag</value>
    </param>
    <param name="pbalign_opts">
        <value>--seed=1 --minAccuracy=0.75 --minLength=50 --algorithmOptions="-useQuality"</value>
    </param>
    <param name="samBam">
        <value>True</value>
    </param>
    <param name="moduleName">
        <value>P_Mapping</value>
    </param>
    <param name="minAnchorSize">
        <value>12</value>
    </param>
    <param name="description">
        <value>BLASR maps reads to genomes by finding the highest scoring local alignment or set of local alignments between the read and the genome. The first set of alignments is found by querying an index of the reference genome, and then refining until only high scoring alignments are retained.  Additional pulse metrics are loaded into the resulting cmp.h5 file to enable downstream use of the Quiver algorithm.</value>
    </param>
    <param name="loadPulsesOpts">
        <value>bymetric</value>
    </param>
    <param name="gff2Bed">
        <value>True</value>
    </param>
  </module>
  <module name="P_MappingReports">
    <param name="moduleName">
        <value>P_MappingReports</value>
    </param>
  </module>
  <module name="P_AssemblyPolishing">
    <param name="moduleName">
        <value>P_AssemblyPolishing</value>
    </param>
    <param name="description">
        <value>Polish a pure-PacBio assembly for maximum accuracy using the Quiver algorithm.</value>
    </param>
    <param name="enableMapQVFilter">
        <value>True</value>
    </param>
  </module>
</smrtpipeSettings>
For AHa assembler also i want to use my fastq subreads and use along with my reference for those its the settings i have used
<?xml version="1.0"?>
<smrtpipeSettings>
  <global>
    <param name="reference">
        <value>/data/results/STLab/pac_bio/unitg/Phyra.utg.fasta</value>
    </param>
  </global>
  <module name="P_Fetch"/>
  <module name="P_Filter">
    <param name="minLength">
        <value>50</value>
    </param>
    <param name="minSubReadLength">
        <value>50</value>
    </param>
    <param name="readScore">
        <value>0.75</value>
    </param>
  </module>
  <module name="P_FilterReports"/>
  <module name="P_AHA">
    <param name="fillin">
        <value>False</value>
    </param>
    <param name="blasrOpts">
        <value>-minMatch 10 -minPctIdentity 70 -bestn 10 -noSplitSubreads</value>
    </param>
    <param name="instrumentModel">
        <value>RS</value>
    </param>
    <param name="paramSchedule">
        <value>6,3,75,100;6,3,75,100;5,3,75,100;6,2,75,100;6,2,75,100;5,2,75,100</value>
    </param>
    <param name="maxIterations">
        <value>6</value>
    </param>
    <param name="description">
        <value>AHA ("A Hybrid Assembler") is the PacBio hybrid assembly algorithm. It is based on the open source assembly software package AMOS, with additional software components tailored to PacBio's long reads and error profile.</value>
    </param>
  </module>
</smrtpipeSettings>

**Comment by mjhsieh** [comment]
This is research related question and beyond the scope of software issue, please contact pacbio field scientists in your region regarding bioinformatics research design. Also perhaps look into protocols like RS_AHA_Scaffolding of smrtanalysis.

**Comment by pb-jlandolin** [comment]
Sorry, SMRT Portal must use the original files (bax.h5) in the original file structure that was produced by the instrument.  See this article for the exact structure: https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Cannot-import-new-SMRT-Cells
