### ISSUE TITLE
Illumina read correction: align2layouts.py missing

### ISSUE THREAD

**Issue by ralfne** [PacificBiosciences/SMRT-Analysis#177]
Hi,
I am trying to run smrtanalysis version 2.3.0 with some test data, doing read correction of long reads with short reads (Illumina 100 bp).I am using a settings.xml file published by PacBio for version 2.3.0. I have no access to the smrtPortal, so I am using the smrtpipe directly from the commandline.
The program crashes, and I have discovered that the reason is the missing align2layouts.py script. This should have been present (apparently) under /smrtanalysis-2.3.0/analysis/bin, but is not there. It is present, however, on older versions, such as version 2.1.1.
I have not installed the pipeline myself, so I do not know exactly what was done... Is there some obvious reason why align2layouts.py would not be included in an installation of smrtanalysis-2.3.0?
Maybe this script comes as an option? How would I go about to install it now? Would it be OK to just copy the align2layouts.py script from version 2.1.1 into version 2.3.0 (if no changes have been made to the script in the meantime...)?

Thank you for any help and feedback!

Ralf

**Comment by rhallPB** [comment]
http://seqanswers.com/forums/showthread.php?t=50709
