### ISSUE TITLE
AHA with no gapFiller request still executes gapFiller.py

### ISSUE THREAD

**Issue by warrenlr** [PacificBiosciences/SMRT-Analysis#181]
I am getting this error running:
pbahaScaffolder.py

<pre>-------
SubProcessError:   File "/gsc/btl/linuxbrew/opt/smrtanalysis/install/smrtanalysis-2.2.0.133377/analysis/bin/gapFiller.py", line 130
    logLevel = logging.DEBUG if self.options.debug else logging.INFO 
                              ^
SyntaxError: invalid syntax
2015-03-06 16:10:27,768 [INFO] Scaffolding failed 
-------</pre>
I believe this code is only supported in newer version of python, not the v2.7 supplied.
But scaffolding appears to have worked prior to that point and, perhaps I would avoid this error if gapFiller.py didn't run by default (even though it is not set and all gap filling options are set to false).

I would appreciate if you could provide a patch of direct me to the portion of the code that calls gapFiller.py

Thanks 
Rene

**Comment by mjhsieh** [comment]
Hi, apparently the syntax is compatible with the v2.7 python that came with smrtanalysis 2.2
```
$ (. current/etc/setup.sh && python)
Python 2.7.3 (default, Jun 29 2013, 06:17:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> logBLAH = 'blah' if False else 'foo'
>>> logBLAH
'foo'
>>>
```
So my first guess is still that at some point other python might be called. If possible, can you share with us how you ran your workflow?

**Comment by warrenlr** [comment]
How does one disable gapFiller.py? Ie what script calls it?
________________________________________
