### ISSUE TITLE
Support for SGE hostgroups

### ISSUE THREAD

**Issue by afif-elghraoui** [PacificBiosciences/SMRT-Analysis#182]
Please note this is an informational post and suggested enhancement.

I did not need a separate queue for SMRTAnalysis, but I have hostgroups on the queue I'm using to distinguish machines by their resources. So I have a hostgroup to collect machines that have the 4GB/core recommended for smrtanalysis.

Say, for example, that my queue is `all.q` and my hostgroup is `@bigMem`. I would run `qsub` with `-q all.q@@bigMem`, In v2.1.1, I modified the qsub template files (`analysis/etc/cluster/SGE/{interactive,start}.tmpl`) to reflect this and it worked out very well.

In version 2.3.0 (I never tested 2.2.0 on SGE, so maybe it's a problem there as well), I get this error in `writeRunCASpec.log` when running HGAP:

```
  File "/share/apps/pacbio/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/runCASpecWriter.py", line 131, in <module>
    kt.start()
  File "/share/apps/pacbio/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/share/apps/pacbio/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/CeleraAssembler/util/SpecWriter.py", line 188, in run
    maxSlotPerc=self.args.maxSlotPerc)
  File "/share/apps/pacbio/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/CeleraAssembler/util/SGEParallelParamsCalculator.py", line 40, in __init__
    self._processQStatOutput(qstatOutput)
  File "/share/apps/pacbio/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/CeleraAssembler/util/SGEParallelParamsCalculator.py", line 66, in _processQStatOutput
    hostprops[kv[0]] = kv[1]
TypeError: 'NoneType' object does not support item assignment
```

I found out this is because the _processQStatOutput() function in SGEParallelParamsCalculator.py (code below) will not properly initialize the hostprops dictionary when a hostgroup is used in `qsub`. The first line of a host block in the `qstat` output has `all.q@hostname`, but the parser will look for a token that starts with `all.q@@bigMem` and so the the first conditional block below will never be true.

```python
        hostprops = None
        host = None

        for l in lines:

            l = l.strip()

            if l.startswith(self._params['queue']):    # This is the problematic line
                hostprops = {}
                host = l.split()[0]

                # add prior
                self._hosts[host] = hostprops

            if l.startswith('hl:num_proc=') or l.startswith('hl:mem_total='):
                kv = l.split('=')
                hostprops[kv[0]] = kv[1]
```

I changed line 57 (the marked 'problematic line' above) of redist/python2.7/lib/python2.7/site-packages/CeleraAssembler/util/SGEParallelParamsCalculator.py to say `if l.startswith(self._params['queue'].split('@')[0]):`. This is a bit of a hack, but it will fix the parser when using hostgroups in the qsub command and does no harm otherwise.

Perhaps this will help anyone who also wants to use hostgroups or help you the developers in case you decide to support this use case.

**Comment by mjhsieh** [comment]
Thanks for your suggestion, I will file a bug for that although no guarantee for this to show up in the next patch. ;-)

**Comment by afif-elghraoui** [comment]
Thanks for considering it. If it doesn't get into the official package, at least the steps to get it working are documented here.
