### ISSUE TITLE
Error while executing resequencing pipeline in consensus (fai not found)

### ISSUE THREAD

**Issue by extemporaneousb** [PacificBiosciences/SMRT-Analysis#183]
I'm getting the following error:

[INFO] Loading reference
Companion FASTA index (.fai) file not found or malformatted! Use 'samtools faidx' to generate FASTA index.

From the call to callVariantsWithConsensus, it states: Use 'samtools faidx' to generate FASTA index.

To what FASTA file is this referring? The one in the ref repo? I uploaded it using refUploader. I'm using the workflow for resequencing found here: 
https://www.dropbox.com/sh/duhw021hzqkwui2/AADpasVY1Sq6edGBLnEm14VRa/RS_Resequencing.1.settings.xml?dl=0 (thanks l. hon) 

thanks, jim

**Comment by extemporaneousb** [comment]
Okay, problem solved. I had to do:

samtools faidx on the refrence repo entry.

**Comment by mjhsieh** [comment]
Reference: current/common/protocols/referenceuploader/ReferenceUploader.1.xml

or from your old memory, it's ```referenceUploader -c -n <name> -p <location> -f <fasta_path> --saw='sawriter -blt 8' --samIdx='samtools faidx'``` for you.

**Comment by extemporaneousb** [comment]
Got it. Thanks, I had always been using:

> referenceUploader -c -n <name> -p <location> -f <fasta_path>
> 
> 

but then never added the other bits. I guess that suffix array is done automatically, but that fasta index is not.


thanks you sir!
