### ISSUE TITLE
SMRTanalysis AMI is NOT able to use r3.8xlarge machines in AWS

### ISSUE THREAD

**Issue by ragowthaman** [PacificBiosciences/SMRT-Analysis#186]
Hi,
I'm trying to run a SMRTanalysis base modification pipeline on AWS (c1.xlarge). However, it always fail at ~45% when the memory runs out. 

It turns out, None of the SMRT AMIs are not compatible with recommended r3.8xlarge (for that matter any of r3s). They instance options became gray/non-selectable in EC2. Is there something I need to do but not doing to enable these machines.

Thanks very much in advance,
Gowthaman

**Comment by pb-jlandolin** [comment]
I seem to be able to select r3.8xlarge instances with the SMRT portal AMI.  Maybe you need to change your region to the East Coast?
