### ISSUE TITLE
Software updates necessary if we have P6 chemistry data?

### ISSUE THREAD

**Issue by roncanepa** [PacificBiosciences/SMRT-Analysis#188]
Hello, I've received back some smart cell data that was prepared with the P6 chemistry.  Are software updates necessary in order to have accurate assembly and methylation analysis results?

For instance, this analysis might take place on the following versions (haven't yet been able to stage an upgrade to the 2.3.x line):
* SMRTAnalysis version v2.2.0 build 133377
* Daemon version v2.2.0 build 132105
* SMRTpipe version v2.2.0 build 132739
* SMRT Portal version v2.2.0 build 133335
* SMRT View version v2.2.0 build 132578

Thank you.

**Comment by mjhsieh** [comment]
Yes, please do. Reference: https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Analysis-Release-Notes-v2.3.0#New
