### ISSUE TITLE
hgapAlignForCorrection fails due to big fasta input (>4Gbytes)

### ISSUE THREAD

**Issue by JPascualAnaya** [PacificBiosciences/SMRT-Analysis#191]
I was trying to run HGAP3.0 under smrtpipe.py (genome size ~300Mbp, so Portal not an option), and got an error on hgapAlignForCorrection, due to >4Gb input fasta files. 

I found around that I should use the option --distribute, but I am running the pipeline in a local server (24 cores, 512Gb). While PBcR was able to finish in about 10 days, I wonder if I can overcome this problem with the fasta input that the smrtpipe is generating. 

The end of hgapAlignForCorrection.log:
```
rcode=$?
echo "Finished on $(date -u)"
echo "Task hgapAlignForCorrection with nproc 23 with exit code ${rcode}."
exit ${rcode}# Writing stdout and stderr from Popen:
Setting up ENV on R910 for task hgapAlignForCorrection
Running task://Anonymous/P_PreAssemblerDagcon/hgapAlignForCorrection on Linux R910 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Started on Wed Apr  1 09:21:13 UTC 2015
Validating existence of Input Files
Successfully found /home/champi/Documents/TerebrataliaGenome/assemblies/HGAP3/data/filtered_subreads.fasta
Successfully found /home/champi/Documents/TerebrataliaGenome/assemblies/HGAP3/filtered_longreads.fasta
Successfully validated input files
[INFO] 2015-04-01T18:21:13 [blasr] started.
ERROR! Reading fasta files greater than 4Gbytes is not supported.
```
Thanks,
Juan

**Comment by jkaralius** [comment]
Hi Juan,

This issue is addressed in the following SeqAnswers thread:

http://seqanswers.com/forums/showthread.php?t=42733

Best,

Joey
