### ISSUE TITLE
Is it possible to update the DNSNAME?

### ISSUE THREAD

**Issue by roncanepa** [PacificBiosciences/SMRT-Analysis#192]
I installed smrtportal using a script similar to this one:

```
su user_name - -c "bash smrtanalysis_2.3.0.140936.run \
--rootdir /scratch/lfs/user_name/smrtanalysisv2.3 \
--patchfile smrtanalysis-patch_2.3.0.140936.p2.run \
--skip-userquery \
--ignore-syscheck \
--dnsname 127.0.0.1 \
--smrtportal-main-port 8080 \
--smrtportal-shutdown-port 8006 \
--tmpdir /tmp \
--skip-userdataquery \
--dbport 53306 \
--jmstype NONE \
--numprocs 2 \
--batch"
```

only to realize much later that the system uses the DNSNAME as the basis for the smrtportal api update calls.  Which makes sense, except that I can't find anywhere to change it, and I've even grep'd through the entire install directory.

Is it possible to change this value without reinstalling?

**Comment by roncanepa** [comment]
I just found the `host` key in current/etc/config.xml and will see if changing that makes a difference.

**Comment by jkaralius** [comment]
Hi roncanepa,

It sounds like you figured this out already.  For the record, change the `name` attribute in the following line of `$SMRT_ROOT/current/etc/config.xml` to the new hostname or IP address.

```
<host httpport="8080" httpsport="" name="[hostname or IP]" />
```

And don't forget to restart the smrtportal daemon:

```
$SMRT_ROOT/cureent/admin/bin/smrtportald-initd restart
```

Best,

Joey
