### ISSUE TITLE
how to do subread filtering by command line?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/SMRT-Analysis#194]
Dear PacBio developers,

I want to do subread filtering on some bax.h5 files, but unfortunately, some data cannot be imported into smrtportal (without a reason), is there a way to do subread filtering by command line? What are the arguments used by smrtportal?

Thanks!

Best,
Yunfei

**Comment by mjhsieh** [comment]
The log and script can be found in the job directories,  you can try to run a demo job and see if you can find the workflow shell scripts.

**Comment by pb-jlandolin** [comment]
Yes, look in the job_id/workflow directory for the exact commands to call.
