### ISSUE TITLE
smrt assembly issue: task adapterRpt FAILED 

### ISSUE THREAD

**Issue by newlbs** [PacificBiosciences/SMRT-Analysis#197]
Hi, I am trying to do genome assembly using pacbio reads through command line. I had the test data working so I assume my smrt anaysis package is installed correctly. However when I tried to run my own data, it failed at the early step as shown in the smrtpipe.log:
```
[INFO] 2015-04-18 10:25:05,435 Successfully found 4 files in xml:input.xml
[INFO] 2015-04-18 10:25:05,496 smrtpipe.py running on bhc0079
[INFO] 2015-04-18 10:25:05,496 SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2015-04-18 10:25:07,639 Process id 18492
[INFO] 2015-04-18 10:25:13,446 Starting task://Anonymous/P_Fetch/toFofn
[INFO] 2015-04-18 10:25:13,447 task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2015-04-18 10:25:13,448 Workflow Completion Status 1/47 in (            2%) tasks completed.
[INFO] 2015-04-18 10:25:18,476 Starting task://Anonymous/P_Mapping/align.plsFofn.Scatter
[INFO] 2015-04-18 10:25:18,476 Starting task://Anonymous/P_Fetch/overviewRpt
[INFO] 2015-04-18 10:25:18,476 Starting task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-04-18 10:25:18,479 task P_Mapping.align.plsFofn.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2015-04-18 10:25:18,479 Workflow Completion Status 2/47 in (            4%) tasks completed.
[ERROR] 2015-04-18 10:25:18,479 *** Failed task task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-04-18 10:25:19,845 task P_Fetch.overviewRpt successfully completed (1.00 sec (0.02 min)). freed 1 slots, using 1 slots.
[INFO] 2015-04-18 10:25:19,845 Workflow Completion Status 3/47 in (            6%) tasks completed.
[INFO] 2015-04-18 10:25:19,846 Found 1 failed tasks.
[INFO] 2015-04-18 10:25:19,846 task adapterRpt FAILED 
Failed smrtpipe version v1.87.139483 with exit code -1 in 15.66 seconds (0.26 minutes)
```
My input.xml is as follows:
```
<?xml version="1.0"?>
<pacbioAnalysisInputs>
  <dataReferences>
    <url ref="run:0000000-0000"><location>/home/bli16/scratch/bli16/pacbio/JKS1/Run_150_347/E09_1/m150314_135807_42153_c100790582550000001823177509091594_s1_p0.mcd.h5</location></
url>
    <url ref="run:0000000-0001"><location>/home/bli16/scratch/bli16/pacbio/JKS1/Run_150_347/F09_1/m150314_181712_42153_c100790582550000001823177509091595_s1_p0.mcd.h5</location></
url>
    <url ref="run:0000000-0002"><location>/home/bli16/scratch/bli16/pacbio/JKS1/Run_150_347/G09_1/m150314_223952_42153_c100790582550000001823177509091596_s1_p0.mcd.h5</location></
url>
    <url ref="run:0000000-0003"><location>/home/bli16/scratch/bli16/pacbio/JKS1/Run_151_348/B01_1/m150318_214858_42153_c100793012550000001823170910081521_s1_p0.mcd.h5</location></
url>
  </dataReferences>
</pacbioAnalysisInputs>
```
 
My `params.xml` is almost the same as the example except I changed the genome size and coverage accordingly:

```
<?xml version="1.0"?>
<smrtpipeSettings>
  <global>
    <param name="version">
        <value>3</value>
    </param>
    <param name="fetch">
        <value>~/scratch/bli16/smrt/current/common/protocols/preprocessing/Fetch.1.xml</value>
    </param>
    <param name="state">
        <value>active</value>
    </param>
    <param name="Control Filtering">
        <value>~/scratch/bli16/smrt/current/common/protocols/control/KeepControlReads.1.xml</value>
    </param>
    <param name="assembly">
        <value>~/scratch/bli16/smrt/current/common/protocols/assembly/PreAssemblerHGAP.3.xml</value>
    </param>
    <param name="consensus">
        <value>~/scratch/bli16/smrt/current/common/protocols/consensus/AssemblyPolishing.1.xml</value>
    </param>
    <param name="description">
        <value>(BETA) HGAP version 3. PacBio de novo assembler optimized for speed.</value>
    </param>
    <param name="filtering">
        <value>~/scratch/bli16/smrt/current/common/protocols/filtering/PreAssemblerSFilter.1.xml</value>
    </param>
    <param name="mapping">
        <value>~/scratch/bli16/smrt/current/common/protocols/mapping/BLASR.1.xml</value>
    </param>
    <param name="otfReference">
        <value>reference</value>
    </param>
    <param name="referenceUploader">
        <value>~/scratch/bli16/smrt/current/common/protocols/referenceuploader/ReferenceUploaderUnitig.1.xml</value>
    </param>
    <param name="deferRefCheck">
        <value>True</value>
    </param>
    <param name="name">
        <value>RS_HGAP_Assembly_3</value>
    </param>
  </global>
  <module name="P_Fetch">
    <param name="moduleName">
        <value>P_Fetch</value>
    </param>
    <param name="description">
        <value>Sets up inputs</value>
    </param>
  </module>
  <module name="P_Filter">
    <param name="moduleName">
        <value>P_Filter</value>
    </param>
    <param name="minSubReadLength">
        <value>500</value>
    </param>
    <param name="description">
        <value>Filter reads for use in the pre-assembly step of HGAP, the hierarchical genome assembly process.</value>
    </param>
    <param name="minLength">
        <value>100</value>
    </param>
    <param name="readScore">
        <value>0.80</value>
    </param>
  </module>
  <module name="P_FilterReports">
    <param name="moduleName">
        <value>P_FilterReports</value>
    </param>
  </module>
  <module name="P_PreAssemblerDagcon">
    <param name="minLongReadLength">
        <value>1000</value>
    </param>
    <param name="totalBestn">
        <value>24</value>
    </param>
    <param name="minCorCov">
        <value>6</value>
    </param>
    <param name="moduleName">
        <value>P_PreAssemblerDagcon</value>
    </param>
    <param name="splitBestn">
        <value>10</value>
    </param>
    <param name="targetChunks">
        <value>6</value>
    </param>
    <param name="computeLengthCutoff">
        <value>True</value>
    </param>
    <param name="blasrOpts">
        <value>-noSplitSubreads -minReadLength 200 -maxScore -1000 -maxLCPLength 16</value>
    </param>
    <param name="title">
        <value>Using DAG-based consensus algorithm, pre-assemble long reads as the first step of the Hierarchical Genome Assembly process (HGAP). Version 2 is a stepping stone for
 scaling to much larger genomes.</value>
    </param>
  </module>
  <module name="P_AssembleUnitig">
    <param name="merSize">
        <value>14</value>
    </param>
    <param name="defaultFrgMinLen">
        <value>500</value>
    </param>
    <param name="moduleName">
        <value>P_AssembleUnitig</value>
    </param>
    <param name="ovlMinLen">
        <value>40</value>
    </param>
    <param name="libraryName">
        <value>pacbioReads</value>
    </param>
    <param name="specTmpl">
        <value>/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/analysis/etc/celeraAssembler/unitig.spec</value>
    </param>
    <param name="description">
        <value>This module runs Celera Assembler v8.1 to the unitig step, then finishes with our custom unitig consensus caller</value>
    </param>
    <param name="genomeSize">
        <value>500000000</value>
    </param>
    <param name="ovlErrorRate">
        <value>0.06</value>
    </param>
    <param name="xCoverage">
        <value>4</value>
    </param>
    <param name="maxSlotPerc">
        <value>1</value>
    </param>
  </module>
  <module name="P_ReferenceUploader">
    <param name="moduleName">
        <value>P_ReferenceUploader</value>
    </param>
    <param name="runUploaderUnitig">
        <value>True</value>
   </param>
    <param name="runUploaderHgap">
        <value>False</value>
    </param>
    <param name="sawriter">
        <value>sawriter -blt 8 -welter</value>
    </param>
    <param name="runUploader">
        <value>False</value>
    </param>
    <param name="samIdx">
        <value>samtools faidx</value>
    </param>
    <param name="name">
        <value>reference</value>
    </param>
  </module>
  <module name="P_Mapping">
    <param name="maxHits">
        <value>10</value>
    </param>
    <param name="maxDivergence">
        <value>30</value>
    </param>
    <param name="placeRepeatsRandomly">
        <value>True</value>
    </param>
    <param name="pulseMetrics">
        <value>DeletionQV,IPD,InsertionQV,PulseWidth,QualityValue,MergeQV,SubstitutionQV,DeletionTag</value>
    </param>
    <param name="pbalign_opts">
        <value>--seed=1 --minAccuracy=0.75 --minLength=50 --algorithmOptions="-useQuality"</value>
    </param>
    <param name="samBam">
        <value>True</value>
    </param>
    <param name="moduleName">
        <value>P_Mapping</value>
    </param>
    <param name="minAnchorSize">
        <value>12</value>
    </param>
    <param name="description">
        <value>BLASR maps reads to genomes by finding the highest scoring local alignment or set of local alignments between the read and the genome. The first set of alignments i
s found by querying an index of the reference genome, and then refining until only high scoring alignments are retained.  Additional pulse metrics are loaded into the resulting cm
p.h5 file to enable downstream use of the Quiver algorithm.</value>
    </param>
    <param name="loadPulsesOpts">
 </param>
    <param name="pulseMetrics">
        <value>DeletionQV,IPD,InsertionQV,PulseWidth,QualityValue,MergeQV,SubstitutionQV,DeletionTag</value>
    </param>
    <param name="pbalign_opts">
        <value>--seed=1 --minAccuracy=0.75 --minLength=50 --algorithmOptions="-useQuality"</value>
    </param>
    <param name="samBam">
        <value>True</value>
    </param>
    <param name="moduleName">
        <value>P_Mapping</value>
    </param>
    <param name="minAnchorSize">
        <value>12</value>
    </param>
    <param name="description">
        <value>BLASR maps reads to genomes by finding the highest scoring local alignment or set of local alignments between the read and the genome. The first set of alignments i
s found by querying an index of the reference genome, and then refining until only high scoring alignments are retained.  Additional pulse metrics are loaded into the resulting cm
p.h5 file to enable downstream use of the Quiver algorithm.</value>
    </param>
    <param name="loadPulsesOpts">
        <value>bymetric</value>
    </param>
    <param name="gff2Bed">
        <value>True</value>
    </param>
  </module>
  <module name="P_MappingReports">
    <param name="moduleName">
        <value>P_MappingReports</value>
    </param>
  </module>
  <module name="P_AssemblyPolishing">
    <param name="moduleName">
        <value>P_AssemblyPolishing</value>
    </param>
    <param name="description">
        <value>Polish a pure-PacBio assembly for maximum accuracy using the Quiver algorithm.</value>
    </param>
    <param name="enableMapQVFilter">
        <value>True</value>
    </param>
  </module>
</smrtpipeSettings>
```
The command I used is 
```
smrtpipe.py -D NPROC=3 -D CLUSTER=BASH -D MAX_THREADS=12 --totalCells=4 --params=params.xml xml:input.xml >smrtpipe.log
```

I have also tried to run a single cell data but it just failed at the same step. Can anyone give me an idea what's wrong? Thanks.

**Comment by roncanepa** [comment]
Is there a log file in ./log/P_Fetch? I'm not sure how different the logging will be on the CLI with a redirect, but I use SmrtPortal and often am able to get more information about why a step failed by looking at these sub-logs.

**Comment by newlbs** [comment]
@roncanepa  Thanks for the reply. I ran it again and it stopped at the P_Filter step:

Traceback (most recent call last):
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 634, in execute
    raise WorkflowError(_e_msg)
WorkflowError: task://Anonymous/P_Filter/filter_003of000 Failed task://Anonymous/P_Filter/filter_002of000 Failed task://Anonymous/P_Filter/filter_001of000 Failed

I checked the filter_001of000.log ans it shows as follows:

#!/bin/bash
# Setting up SMRTpipe environment
echo "Setting up ENV on $(uname -n)" for task filter_001of000

SEYMOUR_HOME=/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936
source $SEYMOUR_HOME/etc/setup.sh

# Create the local TMP dir if it doesn't exist
tmp_dir=$(readlink -m "/gpfs/fs2/scratch/bli16/smrt/tmpdir")
if [ ! -e "$tmp_dir" ]; then
   stat=0
   mkdir -p $tmp_dir || stat=$?
   if [[ $stat -ne 0 ]]; then
       echo "SMRTpipe Unable to create TMP dir '/gpfs/fs2/scratch/bli16/smrt/tmpdir' on $(uname -n)" 1>&2
       exit 1
   else
       echo "successfully created or found TMP dir '/gpfs/fs2/scratch/bli16/smrt/tmpdir'"
   fi
elif [[ ! -d "$tmp_dir" ]]; then
   echo "SMRTpipe TMP /gpfs/fs2/scratch/bli16/smrt/tmpdir must be a directory on $(uname -n)" 1>&2
   exit 1
fi

########### TASK metadata #############
# Task            : filter_001of000
# Module          : P_Filter
# Module Version  : 1.7.139483
# TaskType        : None
# URL             : task://Anonymous/P_Filter/filter_001of000
# createdAt       : 2015-04-21 03:52:22.950683
# createdAt (UTC) : 2015-04-21 07:52:22.950694
# ncmds           : 1
# LogPath         : /gpfs/fs2/scratch/bli16/pacbio/denovo/log/P_Filter/filter_001of000.log
# Script Path     : /gpfs/fs2/scratch/bli16/pacbio/denovo/workflow/P_Filter/filter_001of000.sh

# Input       : /gpfs/fs2/scratch/bli16/pacbio/denovo/input.chunk001of000.fofn
# Output      : /gpfs/fs2/scratch/bli16/pacbio/denovo/data/filtered_summary.chunk001of000.csv
# Output      : /gpfs/fs2/scratch/bli16/pacbio/denovo/data/filtered_regions
# Output      : /gpfs/fs2/scratch/bli16/pacbio/denovo/data/filtered_regions.chunk001of000.fofn
#
########### END TASK metadata #############

cd /gpfs/fs2/scratch/bli16/pacbio/denovo/log/P_Filter
# Writing to log file
cat /gpfs/fs2/scratch/bli16/pacbio/denovo/workflow/P_Filter/filter_001of000.sh >> /gpfs/fs2/scratch/bli16/pacbio/denovo/log/P_Filter/filter_001of000.log;



echo "Running task://Anonymous/P_Filter/filter_001of000 on $(uname -a)"

echo "Started on $(date -u)"
echo 'Validating existence of Input Files'
if [ -e /gpfs/fs2/scratch/bli16/pacbio/denovo/input.chunk001of000.fofn ]
then
echo 'Successfully found /gpfs/fs2/scratch/bli16/pacbio/denovo/input.chunk001of000.fofn'
else
echo 'WARNING: Unable to find necessary input file, or dir /gpfs/fs2/scratch/bli16/pacbio/denovo/input.chunk001of000.fofn.'
fi
echo 'Successfully validated input files'

# Task filter_001of000 commands:


# Completed writing Task filter_001of000 commands


# Task 1
filter_plsh5.py --debug --filter='MinReadScore=0.8000,MinSRL=500,MinRL=100' --trim='True' --outputDir=/gpfs/fs2/scratch/bli16/pacbio/denovo/data/filtered_regions --outputSummary=/
gpfs/fs2/scratch/bli16/pacbio/denovo/data/filtered_summary.chunk001of000.csv --outputFofn=/gpfs/fs2/scratch/bli16/pacbio/denovo/data/filtered_regions.chunk001of000.fofn /gpfs/fs2/
scratch/bli16/pacbio/denovo/input.chunk001of000.fofn || exit $?
echo "Task 1 completed at $(date)"



rcode=$?
echo "Finished on $(date -u)"
echo "Task filter_001of000 with nproc 2 with exit code ${rcode}."
exit ${rcode}# Writing stdout and stderr from Popen:
Setting up ENV on bhc0033 for task filter_001of000
Running task://Anonymous/P_Filter/filter_001of000 on Linux bhc0033 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Started on Tue Apr 21 07:52:38 UTC 2015
Validating existence of Input Files
Successfully found /gpfs/fs2/scratch/bli16/pacbio/denovo/input.chunk001of000.fofn
Successfully validated input files
[INFO] 2015-04-21 03:52:40,723 [pbfilter.filter_plsh5 run 594] Processing 1 files in /gpfs/fs2/scratch/bli16/pacbio/denovo/input.chunk001of000.fofn:
[DEBUG] 2015-04-21 03:52:40,723 [pbfilter.filter_plsh5 run 595] ['/home/bli16/scratch/bli16/pacbio/JKS1/Run_150_347/F09_1/Analysis_Results/m150314_181712_42153_c100790582550000001
823177509091595_s1_p0.bas.h5']
[INFO] 2015-04-21 03:52:40,723 [pbfilter.filter_plsh5 run 596] 5 filters:
[DEBUG] 2015-04-21 03:52:40,724 [pbfilter.filter_plsh5 run 597] [<SequencingZMWFilter headers=SequencingZMW >,
 <InsertAdapterFilter  >,
 <ReadScoreFilter headers=Productivity >,
 <MinSubreadLengthFilter  >,
 <MinReadLengthFilter  >]
Traceback (most recent call last):
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/analysis/bin/filter_plsh5.py", line 8, in <module>
    load_entry_point('pbfilter==1.2', 'console_scripts', 'filter_plsh5.py')()
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbfilter/filter_plsh5.py", line 644, in main
    output_summary=output_summary_csv, trim=trim, debug=debug)
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbfilter/filter_plsh5.py", line 604, in run
    trim=trim)
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbfilter/filter_plsh5.py", line 74, in writeFilteredRgnFiles
    pf.writeFilteredRgnFile(rgnDir, trim)
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbfilter/filter_plsh5.py", line 146, in writeFilteredRgnFile
    self._baxH5Reader = BasH5IO.BaxH5Reader(self._plsFN)
  File "/home/bli16/scratch/bli16/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 433, in __init__
    else self._ccsBasecallsGroup
AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'

I'm not sure is it because the input file was wrong? I used bas.h5 as the example file suggested but here it is checking bax.h5?

**Comment by roncanepa** [comment]
You could be on to something.  I didn't have a chance to look through any of your stuff in detail.

So, the older version of the PB platform generated 1 data file in I think a *.bas file.  The newer version of the machines generate a slightly different file structure:  you'll get 1 bas file and usually 3 bax files.  if you have data from the newer one, you'll need all those files.  If you have data from the older one, you might need to run an older version of the smrtanalysis software.

**Comment by jkaralius** [comment]
Hi newlbs,

You have *mcd.h5* files listed in `input.xml`.  The *bax.h5* files should be in there (see below for an example).  For more details, see the section on [Specifying SMRT Pipe Inputs] (https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Pipe-Reference-Guide-v2.3.0#-specifying-smrt-pipe-inputs) in the [SMRT Pipe Reference Guide](https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Pipe-Reference-Guide-v2.3.0).
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pacbioAnalysisInputs>
    <dataReferences>
        <data ref="/opt/smrtanalysis/install/smrtanalysis_2.3.0.139884/common/test/primary/lambda_v210">
            <location>/opt/smrtanalysis/install/smrtanalysis_2.3.0.139884/common/test/primary/lambda_v210/Analysis_Results/m130802_062611_ethan_c100542982550000001823084811241306_s1_p0.2.bax.h5</location>
            <location>/opt/smrtanalysis/install/smrtanalysis_2.3.0.139884/common/test/primary/lambda_v210/Analysis_Results/m130802_062611_ethan_c100542982550000001823084811241306_s1_p0.1.bax.h5</location>
            <location>/opt/smrtanalysis//install/smrtanalysis_2.3.0.139884/common/test/primary/lambda_v210/Analysis_Results/m130802_062611_ethan_c100542982550000001823084811241306_s1_p0.3.bax.h5</location>
        </data>
    </dataReferences>
</pacbioAnalysisInputs>
```

**Comment by newlbs** [comment]
Hi @jkaralius and @roncanepa , thanks for the reply. You guys are right that it is the problem of the input file. Now I switched to bax.h5 file and it is working now. I am closing this thread now.
