### ISSUE TITLE
p3 patch installation error

### ISSUE THREAD

**Issue by mbourgey** [PacificBiosciences/SMRT-Analysis#201]
Hello

I tried to install the p3 patch using this command:
bash smrtanalysis_2.3.0.140936.run --extract-only --patchfile  smrtanalysis-patch_2.3.0.140936.p3.run

and I get this error:
Starting smrtanalysis_2.3.0.140936 self-extraction...
Creating install directory (./smrtanalysis/install/smrtanalysis_2.3.0.140936)...
Extracting smrtanalysis_2.3.0.140936...
Starting smrtanalysis-patch_2.3.0.140936.p3.149763_linux_x86_64_libc-2.5_centos-53 self-extraction...
Creating install directory (./smrtanalysis/install/smrtanalysis-patch_2.3.0.140936.p3.149763_linux_x86_64_libc-2.5_centos-53)...
Extracting smrtanalysis-patch_2.3.0.140936.p3.149763_linux_x86_64_libc-2.5_centos-53...

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
smrtanalysis-patch_2.3.0.140936.p3.run: Error! Encountered unexpected error at 'line 297 smrtanalysis-patch_2.3.0.140936.p3.run', bailing out...

any idea where the problem come from ?

Thank you in advance

Matheiu

**Comment by mjhsieh** [comment]
The patch file might be corrupted, please use http://files.pacb.com/software/smrtanalysis/2.3.0/smrtanalysis-patch_2.3.0.140936.p3.run.md5 to verify your smrtanalysis-patch_2.3.0.140936.p3.run file.

**Comment by mbourgey** [comment]
HI Mjhsieh,

you were right the file was corrupted !

thank you 

Mahtieu
