### ISSUE TITLE
Difference between RS_PreAssembler.2 and RS_ReadsOfInsert?

### ISSUE THREAD

**Issue by roncanepa** [PacificBiosciences/SMRT-Analysis#211]
What's the difference between these two protocols?  The tooltips in Smrtportal don't make it clear.    I've tried googling, and the two lists of protocols + descriptions that I've found are very out of date:

http://files.pacb.com/software/smrtanalysis/1.4/doc/smrtportal/Help/Portal_DEF_PacBio_Protocols.htm

https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Portal-protocols

Thank you.

**Comment by jkaralius** [comment]
Hi @roncanepa 

**RS_PreAssembler** is used to generate a set of long reads for use in _de novo_ genome assembly.  It takes each of the longest reads, aligns ALL other reads against it, performs a trimming step, then computes the consensus.

**RS_ReadsOfInsert** is different in that it aligns only the subreads from a single polymerase read from one ZMW to compute the consensus.  This is the Circular Consensus Sequence (CCS) protocol.

**Comment by roncanepa** [comment]
Thank you.
