### ISSUE TITLE
smrtanalysis IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by prince26121991** [PacificBiosciences/SMRT-Analysis#214]
I executed smrtpipe.py command 
<pre>smrtpipe.py --distribute -D NPROC=20 --output=/home/scbbcluster/nitesh_mpi/smrt1 --params=/home/scbbcluster/nitesh_mpi/params.xml xml:/home/scbbcluster/nitesh_mpi/picro/my_input.xml</pre>
after 3 days it stopped with this error
<pre>WorkflowError: task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_011of015 Failed task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_009of015 Failed task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_004of015 Failed task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_013of015 Failed task://Anonymous/P_PreAssemblerDagcon/hgapFilterM4_008of015 Failed
Failed smrtpipe version v1.87.139483 with exit code -1 in 219975.42 seconds (3666.26 minutes)
</pre>

So I checked hgapFilterM4_0--of0--(all 5 files which is showing failed task)

And I found 
 Each file having a stderr extension file and all having same message
<pre>Traceback (most recent call last):
  File "/home/scbbcluster/smrtanalysis/current/analysis/bin/filterm4.py", line 64, in <module>
    sys.exit(main())
  File "/home/scbbcluster/smrtanalysis/current/analysis/bin/filterm4.py", line 54, in main
    printUniq(qgroup, count)
  File "/home/scbbcluster/smrtanalysis/current/analysis/bin/filterm4.py", line 39, in printUniq
    print r,
IOError: [Errno 28] No space left on device
</pre>
so please help me to sort this out

and one more thing to ask: Is it possible to resume smrt task from where it failed?
<pre>
[root@scbbcluster]# pdsh -a df -h
r2node3: Filesystem            Size  Used Avail Use% Mounted on
r2node3: /dev/sda3              39G  7.0G   30G  20% /
r2node3: tmpfs                  64G     0   64G   0% /dev/shm
r2node3: /dev/sda1            1008M   57M  901M   6% /boot
r2node3: /dev/sda2             193G   21G  163G  11% /opt
r2node2: Filesystem            Size  Used Avail Use% Mounted on
r2node2: /dev/sda3              39G  7.0G   30G  20% /
r2node2: tmpfs                  64G     0   64G   0% /dev/shm
r2node2: /dev/sda1            1008M   57M  901M   6% /boot
r2node2: /dev/sda2             193G   21G  163G  11% /opt
r3node2: Filesystem            Size  Used Avail Use% Mounted on
r3node2: /dev/sda3              39G  7.0G   30G  20% /
r3node2: tmpfs                  64G     0   64G   0% /dev/shm
r3node2: /dev/sda1            1008M   57M  901M   6% /boot
r3node2: /dev/sda2             193G   17G  166G  10% /opt
r2node4: Filesystem            Size  Used Avail Use% Mounted on
r2node4: /dev/sda3              39G  7.0G   30G  20% /
r2node4: tmpfs                  64G     0   64G   0% /dev/shm
r2node4: /dev/sda1            1008M   57M  901M   6% /boot
r2node4: /dev/sda2             193G   16G  167G   9% /opt
r3node1: Filesystem            Size  Used Avail Use% Mounted on
r3node1: /dev/sda3              39G  7.0G   30G  20% /
r3node1: tmpfs                  64G     0   64G   0% /dev/shm
r3node1: /dev/sda1            1008M   57M  901M   6% /boot
r3node1: /dev/sda2             193G   16G  167G   9% /opt
r2node1: Filesystem            Size  Used Avail Use% Mounted on
r2node1: /dev/sda3              39G  7.0G   30G  20% /
r2node1: tmpfs                  64G     0   64G   0% /dev/shm
r2node1: /dev/sda1            1008M   57M  901M   6% /boot
r2node1: /dev/sda2             193G   21G  163G  12% /opt
r3node4: Filesystem            Size  Used Avail Use% Mounted on
r3node4: /dev/sda3              39G   25G   13G  67% /
r3node4: tmpfs                  64G     0   64G   0% /dev/shm
r3node4: /dev/sda1            1008M   57M  901M   6% /boot
r3node4: /dev/sda2             193G   21G  163G  11% /opt
r3node3: Filesystem            Size  Used Avail Use% Mounted on
r3node3: /dev/sda3              39G  7.0G   30G  20% /
r3node3: tmpfs                  64G     0   64G   0% /dev/shm
r3node3: /dev/sda1            1008M   57M  901M   6% /boot
r3node3: /dev/sda2             193G   16G  167G   9% /opt
</pre>

here one more thing to notice that all 5 task was going to rum on r3node4

expecting reply as soon as possible

**Comment by jkaralius** [comment]
Hi @prince26121991

You don't have enough space on the partition where the job files are located.  Note that the `/` partition on r3node4 has only 13G available.

```
r3node4: Filesystem            Size  Used Avail Use% Mounted on
r3node4: /dev/sda3              39G   25G   13G  67% /
r3node4: tmpfs                  64G     0   64G   0% /dev/shm
r3node4: /dev/sda1            1008M   57M  901M   6% /boot
r3node4: /dev/sda2             193G   21G  163G  11% /opt
```

Re-entrant jobs are not supported, so any failed jobs will need to be started from the beginning.
