### ISSUE TITLE
runCaToUnitig request only one pe slot

### ISSUE THREAD

**Issue by iggyB** [PacificBiosciences/SMRT-Analysis#216]
Hi,

Where to make changes that "runCaToUnitig" job would request more pe slots?

This has been bugging us for a while, but now when we run tens of assemblies simultaneously it gets really really annoying. "runCaToUnitig" job asks for one slot and the queue thinks that it can add another bunch of jobs to the same node. But if several "runCaToUnitig" jobs end up on the same node, they hit the memory roof and everything goes boom. The solution would be simply to tell the "runCaToUnitig" job to take whole node. But where to make changes?

After lots of grep'ing and unsuccessful modifications I ask for help here :)

Cheers,
Iggy

**Comment by pbjd** [comment]
The settings are located in a template file under <smrtanalysis_root>/analysis/etc/celeraAssembler/unitig.spec

In that file you'll see a section like this:

sgeScript = -pe @pe @smrtpipeRcNProc
sgeConsensus = -pe @pe 1
sgeOverlap = -pe @pe @ovlThreads
sgeFragmentCorrection = -pe @pe 2
sgeOverlapCorrection = -pe @pe 1

The `@` symbol represents variables that get replaced by computed values based on various factors (genome size, etc).  I'm pretty sure they can be replaced by numbers without a problem, though make sure you back up this file *before* editing.  

The memory blow up likely happens during the overlap stage, so bumping those numbers higher should fix the problem.  Bear in mind that (depending on your cluster) setting them higher can also result in longer waits in the queue.

**Comment by iggyB** [comment]
Thanks for prompt response! 

Yes, I was looking at the script that calculates the @ values and was making manual changes to unitig.spec. Now things run without bumps.
