### ISSUE TITLE
Start smrtanalysis pipeline with fasta/fastq reads, not hd5

### ISSUE THREAD

**Issue by zymidev** [PacificBiosciences/SMRT-Analysis#218]
Hello,

Is it possible to run a command line smrtanalysis protocol, say the bam resequencing pipeline, but starting with fasta/fastq reads instead of starting with hd5s?

Thanks!

**Comment by mjfi2sb3** [comment]
Hi Zymidev,

Did you manage to get this solved? I have the subreads in fastq format and I am trying to figure out how to run hgap3 on the commandline with this fastq as input.

Regards,
/SB

**Comment by rlleras** [comment]
Hello SB,

Unfortunately, it is not possible to run SMRTAnalysis protocols through the smrtpipe.py workflow manager with only FASTA/FASTQ files. There is certain quality information that is not captured in a FASTA/FASTQ file that is necessary for the software included in these bundles to run. If you need to run an assembly, I would recommend using FALCON (GitHub.com/PacificBiosciences/FALCON), which can take FASTA/FASTQ files.

-Roberto (Bfx @ PacBio)

**Comment by mjfi2sb3** [comment]
Thank you for the prompt reply. The thing is that I am assembling an allotetraploid and FALCON, as far as I know, is designed to deal with diploids.

Regards,
/SB

**Comment by rlleras** [comment]
SB,

FALCON would be much more likely to be able to assemble your genome than your HGAP as it turns out, as you are not dealing with a haploid organism that HGAP3 is geared towards assembling. I would spend some time reading through the documentation on the FALCON page and take a stab at assembling your genome with FALCON.

-Roberto

**Comment by mjfi2sb3** [comment]
Roberto,

Thank you for the tip. I will certainly look into that.  I would like to discuss the project with you in a little more details but it is at its early days so I would appreciate it if we could switch to a more private thread if you do not mind.

Kind regards,
/SB
