### ISSUE TITLE
SMRT-Analysis protocol starting with fasta/fastq instead of hd5

### ISSUE THREAD

**Issue by bryantdo** [PacificBiosciences/SMRT-Analysis#219]
Hello,

Is it possible to run a command line smrtanalysis protocol, say the bam resequencing pipeline, but starting with fasta/fastq reads instead of starting with hd5s?

Thanks!

**Comment by mjfi2sb3** [comment]
Hi,

did you find an answer to this one?

/SB

**Comment by bryantdo** [comment]
Nope, just been using hd5s.

**Comment by evolvedmicrobe** [comment]
Fasta files do not have the necessary data for some later downstream processing steps (in particular genomic consensus), so aren't sufficient for most pipelines and so are not supported.

Out of curiosity, why did you want to use FASTA/FASTQ?

**Comment by mjfi2sb3** [comment]
That's because I was given the fastq file of the subreads. I thought I might be able to assemble starting here
