### ISSUE TITLE
RS_ReadsOfInsert Protocal can't be successfully completed

### ISSUE THREAD

**Issue by JoannaLi007** [PacificBiosciences/SMRT-Analysis#221]
It's SMRT Analysis 2.3 with patch, and I used the RS_ReadsOfInsert.1.xml the pipeline provided, but it cant complete, always ended with error info `Successfully exiting smrtpipe version v1.87.139483 with exit code 0 in 33.55 seconds (0.56 minutes)`, I can't figure out why. Could somebody please help?

**Comment by mjhsieh** [comment]
I am curious, are you using this in command line?

**Comment by JoannaLi007** [comment]
Yes, and it is always quit, and my commands are like:
source /../smrtanalysis/current/etc/setup.sh
fofnToSmrtpipeInput.py input.fofn > input.xml
smrtpipe.py -D TMP=/../tmpdir --params=RS_ReadsOfInsert.1.xml xml:input.xml
always quit with error info like I mentioned before.

**Comment by JoannaLi007** [comment]
@mjhsieh   Yes, and it is always quit, and my commands are like:
source /../smrtanalysis/current/etc/setup.sh
fofnToSmrtpipeInput.py input.fofn > input.xml
smrtpipe.py -D TMP=/../tmpdir --params=RS_ReadsOfInsert.1.xml xml:input.xml
always quit with error info like I mentioned before.

**Comment by linz-li** [comment]
JoannaLi007 , have you solve the problem?I had a same problem.

**Comment by evolvedmicrobe** [comment]
We would need a better description to solve this, I would try running the updated version of CCS https://github.com/PacificBiosciences/pbccs
