### ISSUE TITLE
I can't restart SMRT-Analysis

### ISSUE THREAD

**Issue by ramarquezo** [PacificBiosciences/SMRT-Analysis#233]
My SMRT-Analysis started correctly (even I ran some assemblies) but when I tried to restart it I had the following problem:

alejo-lgmb@alejolgmb-HP-Z230-Tower-Workstation:~$ sudo /opt/smrtanalysis/admin/bin/smrtportald-initd start
Password: 
mkdir: cannot create directory '/opt/smrtanalysis/current/common/userdata': File exists
Using CATALINA_BASE:   /opt/smrtanalysis/current/redist/tomcat
Using CATALINA_HOME:   /opt/smrtanalysis/current/redist/tomcat
Using CATALINA_TMPDIR: /opt/smrtanalysis/current/redist/tomcat/temp
Using JRE_HOME:        /opt/smrtanalysis/current/redist/java
Using CLASSPATH:       /opt/smrtanalysis/current/redist/tomcat/bin/bootstrap.jar:/opt/smrtanalysis/current/redist/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /opt/smrtanalysis/current/common/userdata/runtime/run/tomcat/tomcatd.pid
/opt/smrtanalysis/current/redist/tomcat/bin/catalina.sh: 434: /opt/smrtanalysis/current/redist/tomcat/bin/catalina.sh: cannot create /opt/smrtanalysis/current/common/userdata/runtime/run/tomcat/tomcatd.pid: Directory nonexistent

When I launched it on mozilla there wasn't any answer...

**Comment by mhsieh** [comment]
Let's see what's going on with your installation, can we have output of this?
```
ls -l /opt/smrtanalysis/current/common/
```

**Comment by ramarquezo** [comment]
total 28
dr-xr-xr-x  2 alejo-lgmb alejo-lgmb 4096 oct 20 15:13 etc
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   23 oct  1  2014 inputs_dropbox -> userdata/inputs_dropbox
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   13 oct  1  2014 jobs -> userdata/jobs
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   21 oct  1  2014 jobs_archive -> userdata/jobs_archive
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   21 oct  1  2014 jobs_dropbox -> userdata/jobs_dropbox
dr-xr-xr-x  4 alejo-lgmb alejo-lgmb 4096 oct  1  2014 lib
drwxr-xr-x  5 alejo-lgmb alejo-lgmb 4096 oct 20 15:20 log
drwxr-xr-x 12 alejo-lgmb alejo-lgmb 4096 may 11 16:25 protocols
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   19 oct  1  2014 references -> userdata/references
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   27 oct  1  2014 references_dropbox -> userdata/references_dropbox
dr-xr-xr-x  6 alejo-lgmb alejo-lgmb 4096 oct  1  2014 test
lrwxrwxrwx  1 alejo-lgmb alejo-lgmb   17 oct 20 15:05 userdata -> ../../../userdata
drwxr-xr-x  8 alejo-lgmb alejo-lgmb 4096 may 11 16:25 userdata.d
dr-xr-xr-x  3 alejo-lgmb alejo-lgmb 4096 oct  1  2014 www

**Comment by mhsieh** [comment]
Thanks, this directory looks fine. Can I have the output
```
ls -l /opt/smrtanalysis/current/common/../../../userdata
```

**Comment by ramarquezo** [comment]
lrwxrwxrwx 1 alejo-lgmb alejo-lgmb 64 oct 20 15:55 /opt/smrtanalysis/current/common/../../../userdata -> /media/alejo-lgmb/Disc-2-3TB/SMRT-portal-results/offline_storage

**Comment by ramarquezo** [comment]
sorryyy!!! I found the error!!! I had addressed the results to a not mounted hard drive!!!! Thank you so much!!!!!!

**Comment by ramarquezo** [comment]
Sorry mhsieh, I already started the server correctly but I can't still launch it on mozilla? 

Starting database server...
  Successfully started database server (pid: 2862)...
Using CATALINA_BASE:   /opt/smrtanalysis/current/redist/tomcat
Using CATALINA_HOME:   /opt/smrtanalysis/current/redist/tomcat
Using CATALINA_TMPDIR: /opt/smrtanalysis/current/redist/tomcat/temp
Using JRE_HOME:        /opt/smrtanalysis/current/redist/java
Using CLASSPATH:       /opt/smrtanalysis/current/redist/tomcat/bin/bootstrap.jar:/opt/smrtanalysis/current/redist/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /opt/smrtanalysis/current/common/userdata/runtime/run/tomcat/tomcatd.pid
Existing PID file found during start.
Removing/clearing stale PID file.

**Comment by ramarquezo** [comment]
Which one pid port should I use?

**Comment by mhsieh** [comment]
This looks like a clean start. Are you using a 8080 port for the web?

**Comment by ramarquezo** [comment]
Yes I do..

**Comment by ramarquezo** [comment]
http://172.16.64.31:8080/smrtportal/#/Design-Job/

**Comment by mhsieh** [comment]
let's see the output of this command
```
netstat -l -n|grep 8080
```

**Comment by ramarquezo** [comment]
tcp6       0      0 :::8080                 :::*                    LISTEN

**Comment by mhsieh** [comment]
not sure if ipv6 is interfering, but this should give you something.
```
wget -qO- http://localhost:8080/
```

**Comment by ramarquezo** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Pacific Biosciences SMRT&reg; Analysis Server</title>
<style type="text/css">
  body {
    position: relative;
    font-size: 12px; font-family: Arial, sans-serif;
    color: #fff; padding: 0; margin: 0; 
  }
  .container { width: 960px; margin: 0 auto; }
  .shadow-left { 
    -moz-box-shadow: -8px 0px 8px #CCC;
    -webkit-box-shadow: -8px 0px 8px #CCC;
    box-shadow: -8px 0px 8px #CCC;
  }
  .shadow-right {
    -moz-box-shadow: 8px 0px 8px #CCC;
    -webkit-box-shadow: 8px 0px 8px #CCC;
    box-shadow: 8px 0px 8px #CCC;
  }
  .content {
    padding: 8px 16px; 
    background: #687d8c url('/smrtanalysis/background.png') repeat-x; 
  }
  h1 { 
    font-size: 16px; 
    background: url('/smrtanalysis/logo.png') no-repeat; 
    padding: 60px 0 10px 0; 
    border-bottom: 1px solid white;
  }
  .column { float: left; width: 420px; }

  ul { font-size: 16px; list-style: none; margin: 0; padding: 4px 0; }
  li { margin: 8px 0 0 0; padding: 0; font-weight: bold; }
  li li { font-size: 14px; padding-left: 30px; }
  li li li { font-size: 12px; }
  li li a { font-weight: bold; }
  li li li a { font-weight: normal; }
  a { color: white; text-decoration: none; }
  a:hover { color: #DE7728; text-decoration: underline; }
  a:active { color: #0F80D1; }

  .footer { 
    font-size: 9px; 
    clear: both; 
    text-align: center; 
    margin-bottom: 10px;
  }
</style>
</head>

<body>

<div class="container">
<div class="shadow-left"><div class="shadow-right">
<div class="content">

<h1>SMRT<span style="position: relative; vertical-align: top; font-size: 12px;">&reg;</span> Analysis Server v2.3.0</h1>

<div class="column">
  <ul>
    <li>Applications
      <ul>
        <li>SMRT Portal
	  	    <ul>
            <li><a href="/smrtportal">Launch SMRT Portal</a></li>
            <li><a href="/smrtportal/Help/SMRT_Portal.htm">SMRT Portal User Documentation</a></li>
          </ul>
        </li>
        <li>SMRT View
          <ul>
            <li><a href="/smrtview">SMRT View Home Page</a></li>
            <li><a href="/smrtview/axis2-web/app/help/SMRT_View.htm#View_Main.htm">SMRT View User Documentation</a></li>
          </ul>
        </li>
      </ul>
    </li>

    <li>Administration
      <ul>
        <li>SMRT Portal Administration
          <ul>
            <li><a href="/smrtportal/#/Admin/Manage-Users">Manage SMRT Portal Users</a>&nbsp;</li>
            <li><a href="/smrtportal/#/Import-and-Manage/Protocols">Manage Protocols</a></li>
            <li><a href="/smrtportal/#/Import-and-Manage/Reference-Sequences">Manage Reference Sequences</a></li>
          </ul>
        </li>
        <li>Web Server Administration
          <ul>
            <li><a href="/tomcat_index.jsp">Web Server Home Page</a></li>
            <li><a href="/manager/html">Web Application Manager </a></li>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
</div>

<div class="column">
  <ul>
    <li>Documentation
      <ul>
        <li>User Documentation
          <ul>
            <li><a href="/smrtanalysis/doc/README.html">Readme</a></li>
   		    <li><a href="http://www.pacbiodevnet.com">Online Documentation</a></li>
            <li><a href="https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Pipe-Reference-Guide-v2.3.0">SMRT Pipe Reference Guide</a></li>
            <li><a href="/smrtanalysis/doc/bioinformatics-tools">Bioinformatics Analysis Modules Documentation</a></li>
            <li><a href="https://github.com/PacificBiosciences/SMRT-Analysis/issues">Product Feedback</a></li>
          </ul>
        </li>
        <li>Developer Documentation
          <ul>
            <li><a href="https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Secondary-Analysis-Web-Services-API-v2.3.0">SMRT Analysis Web Services API</a></li> 
            <li><a href="/smrtanalysis/doc/smrtportal/apidocs">SMRT Portal API Specification</a></li>
            <li><a href="/smrtanalysis/doc/smrtview/apidocs">SMRT View API Specification</a></li> 
            <li><a href="/smrtanalysis/doc/secondary-common/apidocs">Common API Specification</a></li>
            <li><a href="/smrtanalysis/doc/secondary-analysis/apidocs">Analysis API Specification</a></li>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
</div>

<div class="footer">
  <a href="http://www.pacificbiosciences.com">Copyright&copy; 2010-2013 Pacific Biosciences</a>
</div>

</div>
</div></div>
</div>

</body>
</html>

**Comment by mhsieh** [comment]
How about wget -qO- http://172.16.64.31:8080 ? Do you get the same html output?

**Comment by ramarquezo** [comment]
There isn't nothing and the web page doesn't work...

**Comment by mhsieh** [comment]
this portal instance didn't bind to the ipv4 address successfully. So a question for you, when you install, did you use localhost as the host name for the portal?

**Comment by ramarquezo** [comment]
I think so, but I'm not sure!

**Comment by mhsieh** [comment]
localhost might not be a good idea. but I want to make sure that we are on the right track. Can we see the output of ``ifconfig -a|grep addr``` ?

**Comment by mhsieh** [comment]
(also if possible, try disable ipv6)

**Comment by ramarquezo** [comment]
Sorry for the delay mhsieh, I had to leave the office. The output for ifconfig -a|grep addr is:

eth0      Link encap:Ethernet  HWaddr 2c:44:fd:37:a4:b5  
          inet addr:172.16.64.27  Bcast:172.16.64.63  Mask:255.255.255.192
          inet6 addr: fe80::2e44:fdff:fe37:a4b5/64 Scope:Link
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host

**Comment by mhsieh** [comment]
not clear what to proceed at this moment, since I normally would recommend disabling ipv6. But since @ramarquezo "reinstalled" the smrtanalysis, we probably should close this.
