### ISSUE TITLE
Can SMRT Portal run on CentOS 6.7?

### ISSUE THREAD

**Issue by nataschamay** [PacificBiosciences/SMRT-Analysis#238]
Hi,

Our SMRT Portal is currently installed on CentOS 6.3 as required. However, we are facing numerous dependency issue for other tools that we want to install and run which require newer versions of core libraries (such as libc and libz). Our IT personnel suggested that the best way around these issues is to upgrade to a newer version of CentOS.

May I know if doing an upgrade to CentOS 6.7 or CentOS 7 will affect SMRT Portal / SMRT Analysis?

Thank you!

Regards,
Natascha

**Comment by mjhsieh** [comment]
Hi, Which version of SMRT Portal are you using? Thanks/

**Comment by nataschamay** [comment]
Hi, 

I'm so sorry for my delayed reply. Below are the version information from SMRT Portal:

**SMRT Analysis**
smrtanalysis_2.3.0.140936.p2.144836

**Components**
Daemon 2.3.0.139497
SMRTpipe 2.3.0.139497
SMRT Portal 2.3.0.140893
SMRT View 2.3.0.140836 

Thank you!

Regards,
Natascha

**Comment by mhsieh** [comment]
For some reason I missed the notification of your reply. But the answer is yes. It should be compatible. Please do let us know if you have problem running it.
