### ISSUE TITLE
can not delete cells from smrt portal

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/SMRT-Analysis#239]
Hi, I tried to follow the instructions at https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Delete-SMRT-Cells-from-SMRT-Portal but was unable to find the cell number.

$ curl -H "Accept: text/tsv" -d 'options={"rows":0,"columnNames":["inputId","sampleName"]}' http://localhost:8080/smrtportal/api/inputs/
{
  "type" : "com.pacbio.secondary.smrtportal.common.rest.UnauthorizedException",
  "errors" : null,
  "success" : false,
  "message" : "Unauthorized"
}

Any suggestions would be greatly appreciated.

Best,
Jason

**Comment by mjhsieh** [comment]
Have you try adding ```-u "administrator:adminpassword"``` to your curl string?

**Comment by ishengtsai** [comment]
Ah. sorry for the rookie mistake. Thank you and it's solved.

**Comment by mjhsieh** [comment]
I just realized that I read your recent blog, a good read. :-)

**Comment by ishengtsai** [comment]
Thanks for interest in reading my blog. :) Hope we can work on something
together sometimes.

**Comment by bretonics** [comment]
Wiki page https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Delete-SMRT-Cells-from-SMRT-Portal needs update to reflect `-u "administrator:adminpassword"`
