### ISSUE TITLE
resume failed analysis

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/SMRT-Analysis#244]
Dear smrtanlaysis developers,

I wonder if there is a way to resume failed jobs in smrtanalysis? If I run `job.sh`, will the analysis pick up where it failed? I have a large job, and it always fails due to small problems (memory, job splitting) that are easy to fix. It is huge waste of time to start over every time. Thanks!

**Comment by mhsieh** [comment]
Hi, You can always run the tasks in the workflow directory, but a simple answer is no, we don't support job resumption in smrtanalysis 2.3.

**Comment by yunfeiguo** [comment]
Got it. Thanks!
