### ISSUE TITLE
Where is SMRT-Analysis v3.0

### ISSUE THREAD

**Issue by afinit** [PacificBiosciences/SMRT-Analysis#249]
I'm reading that I need SMRT-Analysis v3.0, but I can't seem to find it anywhere. The most 

I really only care about finding the updated software, but the following was also an issue I encountered.

I tried signing up for the Customer Portal Access to get tech support, but I'm getting an error that says 'Organization is Required'. Organization is not an available field here.

**Comment by afif-elghraoui** [comment]
Related: https://github.com/PacificBiosciences/SMRT-Link/issues/10

**Comment by evolvedmicrobe** [comment]
I believe the previous link answered this question.
