### ISSUE TITLE
Can smrtanalysis tools be run across multiple compute nodes?

### ISSUE THREAD

**Issue by puapinyoying** [PacificBiosciences/SMRT-Analysis#251]
Hi,

I am a bit new to cluster computing and had a question about the best way to make use of our resources.  Are the tools called by ConsensusTools.sh, pbtransript.py (classify & cluster) and tofu-wrap.py able to run across multiple compute nodes? Or do I need to divide my data and run them on single nodes?

We setup smrtAnalysis p5 on our university HPC cluster to run the IsoSeq pipeline. Our cluster uses SLURM to manage our jobs.  So far I am able to run 'ConsensusTools.sh CircularConsensus' on a one node per job basis, but I am wondering if this is the most optimal way of running the jobs? It would be great if I could assign more nodes when it comes time to run the classify and cluster steps.

Thanks,
Brian

**Comment by mhsieh** [comment]
Solved by Roberto

**Comment by puapinyoying** [comment]
Roberto's answer: the programs do not employ mpi so they cannot be run across multiple nodes.
