### ISSUE TITLE
Can't find ConsensusTools

### ISSUE THREAD

**Issue by bretonics** [PacificBiosciences/SMRT-Analysis#254]
I can't find the command-line program `ConsensusTools` within my SMRT Analysis installation. What's the location? Haven't found it under any directory/subdirectory

**Comment by evolvedmicrobe** [comment]
You should be able to use the unix find command, e.g.

    find . -name "*ConsensusTools*"

**Comment by bretonics** [comment]
I already did using -iname flag, but I completely missed it (don't know how that happened). Thought I was missing something; silly me. Anyways, it's here:

>/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin

Thanks @evolvedmicrobe
