### ISSUE TITLE
Samtools Version

### ISSUE THREAD

**Issue by bretonics** [PacificBiosciences/SMRT-Analysis#263]
Why does SMRT Analysis come with/use samtools version `0.1.19` and not the latest `1.3.*`?

Is this being upgraded in the new portal release?

**Comment by evolvedmicrobe** [comment]
Most of the SAM/BAM operations are performed by our own toolchain which builds off htslib:  https://github.com/PacificBiosciences/pbbam 

Older versions of samtools may have been used during the transition.
