### ISSUE TITLE
Reference file upload fails with colon in header

### ISSUE THREAD

**Issue by bretonics** [PacificBiosciences/SMRT-Analysis#264]
As in issue #161, upload fails using the portal **or** `referenceUploader` to upload a file with a colon in header.
> ':' character is not allowed in the header. Terminating.

I don't think this should be an issue when the file is correct FASTA format, and the header should just be a string. Any particular reason why it rejects the colons?

**Comment by mpkocher** [comment]
This is to ensure that downstream files are well formed (e.g., gff).

For SMRTLink Analysis 3.x, please see the updated docs for more details.

http://pacbiofileformats.readthedocs.io/en/3.0/FASTA.html
