### ISSUE TITLE
Tools to get reads of insert.

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/SMRT-Analysis#279]
Hi!

I want to know how to get ROI from h5 file? It seemed I can use pbccs, pbh5tools, ConsensusTools.sh CircularConsensus from command line, or use P_fetch, P_filter module according to SMRT Pipe Reference Guide. I am confuse about the relationship of these tools, I guess when running in SMRT Pipe way with P_fetch, P_filter, it would use "ConsensusTools.sh CircularConsensus", and I want to konw:

1) Did ConsensusTools.sh CircularConsensus use pbccs, pbh5tools, or it use other scripts?

2) When use SMRT Pipe, how can I know what scripts were used, so I can run it step by step? I had run a demo only with P_fetch, P_filter, P_filter_report model, and tried to find these scripts by "cat *sh" file, are there a convenient way?

Any suggestion would be grateful!

**Comment by evolvedmicrobe** [comment]
Hi,

In answer to your question - `ConsensusTools.sh CircularConsensus` runs an older version of our CCS algorithm, the new version is pbccs.

2 - With SMRT Pipe, it should produce log files at every stage that you can view.

Cheers,
N

**Comment by lamz138138** [comment]
Hi!

Thanks for your reply!
