### ISSUE TITLE
CCS read module?

### ISSUE THREAD

**Issue by quattrinia** [PacificBiosciences/SMRT-Analysis#286]
Hi,

I am trying to generate CCS reads (as described here https://github.com/PacificBiosciences/SMRT-Analysis/wiki/ConsensusTools-v2.3.0-Documentation)  from raw PacBio Data using the Amazon Web Services. I have successfully uploaded data, and found the smrtanalysis package on AWS. However, I cannot seem to locate any of the modules described. Can anyone point me in the right direction?

Thank you~

**Comment by evolvedmicrobe** [comment]
Hi @quattrinia ,

I would recommend just running CCS directly.  See the installation and instructions at: https://github.com/PacificBiosciences/pbccs 

I am not sure exactly which modules you mean.  If the SMRT Analysis tools are on the path, `ConsensusTools.sh CircularConsensus` would be the command line option to run it.  See: https://github.com/PacificBiosciences/SMRT-Analysis/wiki/ConsensusTools-v2.3.0-Documentation#command-line-interface

**Comment by evolvedmicrobe** [comment]
Am closing this for now, feel free to reopen if your problem isn't solved.
