### ISSUE TITLE
Can SMRTtools be installed on MacOS OS X 10.10.5 (Darwin 14.5.0)

### ISSUE THREAD

**Issue by danwiththeplan** [PacificBiosciences/SMRT-Analysis#302]
Is this possible and is there a guide somewhere? I am following http://www.pacb.com/wp-content/uploads/2015/09/SMRT-Analysis-Software-Installation-v2.3.0.pdf and running into a lot of issues. Firstly, you need to explicitly create the smrtanalysis user and group. Then 'libc' is not there. This is simply to allow for small-scale demonstrations on a laptop (not for production scale use). Is it more sensible to just use the [SMRT Portal AMI](https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/%22Installing%22-SMRT-Portal-the-easy-way---Launching-A-SMRT-Portal-AMI) or just run Ubuntu on virtualbox or something?

**Comment by jkaralius** [comment]
Installation of SMRT Analysis is not officially supported on MacOS, so we cannot provide guidance on how to do this.  I have heard of users attempting installation on MacOS, but to my knowledge none were successful nor do we have documented evidence of what steps were taken.  I recommend either installing onto a VM running supported OS, or launching the SMRT Analysis AMI.

**Comment by danwiththeplan** [comment]
Thanks, appreciate the feedback.
